### ISSUE TITLE
LruCache returns partial record for QUERY_ROOT resulting in cache lookup failure

### ISSUE THREAD

**Issue by edenman** [apollographql/apollo-kotlin#2013]
**Summary**
I am trying to load a record from the Apollo cache.  I know the record exists in the SQL cache.  However, `LruNormalizedCache` has an incomplete record for `QUERY_ROOT` that it returns from `loadRecord` so the entire cache lookup fails.  Steps:
- Load FooQuery such that there are more than `maxEntries` things inserted into the `lruCache`
- Perform a small mutation.  LruNormalizedCache will insert this new incomplete `QUERY_ROOT` because `performMerge` doesn't check `nextCache` before storing the result
- Try to load FooQuery from the cache (`apolloClient.apolloStore().read(query).execute()`) and get an exception that the record couldn't be loaded.

I'm going to try to write a testcase that shows this bug but I'm having trouble importing this project into AS.

**Version**
1.3.2

**Comment by martinbonnin** [comment]
Hi 👋 . Indeed, I don't think we have such a test case at the moment. Maybe it's working on `dev-3.x`, maybe the bug is still there. In all cases we should add a test case. If you feel like it, the IDE situation is way better now than it was one year ago.

You can open the `apollo-android/tests` composite project in a recent IntelliJ and it should work fine. Feel free to send a PR. Or if it's been way too long since last year, we'll get on it at some point.
