### ISSUE TITLE
WebSocket support for JS targets

### ISSUE THREAD

**Issue by omainegra** [apollographql/apollo-kotlin#2463]
**Is your feature request related to a problem? Please describe.**

- Many projects include a JS target. Supporting JS targets will increase Apollo’s viability when being considered for multi-platform projects.
- It is not straightforward to use Apollo in projects that include a JS target. This is due to the `apollo-runtme-kotlin` artifact, which can’t be used in `commonMain`. One workaround is to include `apollo-runtime-kotlin-jvm` in `androidMain` and `apollo-runtime-kotlin-ios-x64` in `iosMain`, then write dozen of expect/actual to fill the gap in `jsMain`

**Describe the solution you'd like**

- Add `js` target in the build definition.
- Provide `actual` implementations for the required classes (i.e `ApolloHttpNetworkTransport`).
- Probably many more things.

**Comment by martinbonnin** [comment]
Linking the work in progress in that issue: 
* https://github.com/apollographql/apollo-android/pull/2467
* https://github.com/apollographql/apollo-android/pull/2482

**Comment by martinbonnin** [comment]
`apollo-api` will be able to target JS with `2.2.4` (see #2467). Updated todo list:

- [x] add a JS target to `apollo-api`
- [ ] implement `ApolloHttpNetworkTransport` for JS
- [ ] implement `WebSocketFactory` for JS

**Comment by Pitel** [comment]
Hello. What is the state of this? Can I use Apollo clien in my JS project now, even partialy? Is there some documentation/example?

**Comment by martinbonnin** [comment]
We're getting there (thanks @Pitel 💙 !). Updated the title of this issue to reflect the fact that only `WebSockets` are missing now.

**Comment by undermark5** [comment]
I may be interested in tackling at least part of the issue at hand. I'm assuming that without Websocket support there is no subscription support for the Kotlin/JS client. Is that the case? I wrote myself a incredibly basic implementation of a client built around Ktor that supports subscriptions due to being unable to find a GraphQL client that supported subscriptions and Kotlin/JS without having to figure out how to write the proper adapters for the various JS clients. I've read [CONTRIBUTING](https://github.com/apollographql/apollo-kotlin/blob/main/CONTRIBUTING.md) and it seems like having a discussion here is the proper place to start to understand the details, requirements, etc.

**Comment by undermark5** [comment]
Ok, so apparently ktor 1.6.7 doesn't support js client websockets, so I used vanilla JS WebSockets I've drafted the PR (linked above and again here #3913)

**Comment by undermark5** [comment]
So, I've realized an issue in the implementation, currently, it fails to end the subscription if the websocket is closed on the remote connection, should I open a new issue or just reference this one again?

**Comment by martinbonnin** [comment]
It wasn't released yet so I'd say it's fine to reuse this issue 😊
