### ISSUE TITLE
[iOS] Kotlin Runtime interoperability with multithreaded Kotlin/Native environment

### ISSUE THREAD

**Issue by andersio** [apollographql/apollo-kotlin#2916]
**Is your feature request related to a problem? Please describe.**
While #2619 and #2619 were marked as solved since forcing dependency can work, there are still a few pending issues after my recent attempt:

1. Both `ApolloHttpNetworkTransport` and `ApolloWebSocketNetworkTransport` have preconditions on callers having to be on the main thread. So requests cannot be started on any non-Main dispatcher.

2. `ApolloWebSocketNetworkTransport` has mutable internal state and cannot be frozen, making it hard to use with native-mt in practice.

     Classes with mutable state cannot be frozen, or otherwise mutation attempt will throw exceptions at runtime. So even if I can satisfy the preconditions in (1) by manually applying `flowOn(Dispatchers.Main)`, I cannot reference the WSTransport class in any entities that is frozen because it _might_ not run on the main thread.

**Describe the solution you'd like**
1. `ApolloWebSocketNetworkTransport` should be altered to be a Kotlin/Native multithreading friendly. Similar modifications should be done for `ApolloHttpNetworkTransport`.

    Mutable content must all be converted into constructs that can be frozen, e.g. packed into immutable classes, and use `AtomicReference<T>` for mutability.

2. Lift the main-thread-only restrictions in the iOS implementations.

    In the stable native distribution of Kotlin Coroutines, all the in-built dispatchers run on the main thread anyway. So the checks don't seem to add value for the stable dist, while they are preventing background use in the native-mt variant.

3. Support `NSURLSession`s with a non-main delegate queue.

    The default can remain to be the main queue, of course.

**Comment by martinbonnin** [comment]
Hi 👋 ! Thanks for the detailed feedback. There can definitely be some improvements around the native multi-threading. 

One question:

>  I cannot reference the WSTransport class in any entities that is frozen because it might not run on the main thread.

My current understanding is that callers only reference `ApolloWebSocketNetworkTransport` when creating the `ApolloClient`. Do you need to hold references in other places too? I was under the impression that creating the `ApolloClient` from the main thread would be a workaround but maybe I'm missing something.

**Comment by sav007** [comment]
For the context:

>In the stable native distribution of Kotlin Coroutines, all the in-built dispatchers run on the main thread anyway. So the checks don't seem to add value for the stable dist, while they are preventing background use in the native-mt variant.

Technically you can run coroutines on any thread ( not particularly on main thread) as long as you stay at the same one and don't switch the context. The enforcement for use only main thread comes from the how http network is executed. When we execute http call on iOS we schedule it to run on background queue. But the issue is that after http call is executed we need to return to the caller thread. Now there is no way you can do it except main thread that is the only one. 

That means we enforce coroutine to run on main thread so we can store pointer to continuation to resume coroutine execution after we come back from executing network call.

Now related to `coroutines-mt` that for sure smth that we are planing to look into. We should be careful with this though, as far as I remember this branch is not stable and subject to change completely later by Kotlin team. There is no guarantee that the behaviour going be the same as they might rework memory model for KN and lift some restriction on mutability.

**Comment by martinbonnin** [comment]
Hi @andersio , can you share more details about your use case and why you need to share `ApolloWebSocketNetworkTransport` from multiple threads and/or call queries from a non-main thread? As we're working on the 3.x runtime, it'd be a good time to see if we can support more use cases.

**Comment by BoD** [comment]
With [v3.5.0](https://github.com/apollographql/apollo-kotlin/releases/tag/v3.5.0), Apollo Kotlin uses the new native memory manager, which removes the main thread as well as mutable state/freezing restrictions we used to have.

With that, marking this one as fixed but don't hesitate to re-open if more Kotlin/Native friendly changes can be made!
