### ISSUE TITLE
Spring Boot AutoConfiguration

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-kotlin#3289]
Similar to https://github.com/freefair/okhttp-spring-boot, add support for [Spring Boot Autoconfiguration](https://docs.spring.io/spring-boot/docs/2.0.x/reference/html/using-boot-auto-configuration.html)

The url could be set as a `application.yml` property: `apollo.client.server-url=https://some-site.com/graphl` so that the `ApolloClient` is made available automatically.

**Comment by csabakos** [comment]
The auto-configuration should also make sure that the
* `okHttpClient`
* `dispatcher`

properties that get used for creating `ApolloClient` are Spring beans, so that auto-instrumentation frameworks that use bean postprocessors (such as [Spring Cloud Sleuth](https://spring.io/projects/spring-cloud-sleuth)) work out of the box.

**Comment by martinbonnin** [comment]
Closing as out of scope. We're welcoming 3rd party integrations though. If anyone gets to it, please share it and we'll add it to [the list](https://www.apollographql.com/docs/kotlin/#community-integrations)!
