### ISSUE TITLE
The default value of `useSchemaPackageNameForFragments` is set to false and it causing breaking changes

### ISSUE THREAD

**Issue by kubode** [apollographql/apollo-kotlin#3855]
**Summary**
`useSchemaPackageNameForFragments` introduced in #3775 is causing a breaking change on my KMM project.

**Version**
3.1.0

**Description**

`build.gradle.kts`
```kotlin
apollo {
    packageNamesFromFilePaths("my.package.name")
}
```

Project structure
- src
  - commonMain
    - graphql
      - fragment
        - MyFragment.graphql
      - query
        - MyQuery.graphql

In 3.0.0, this configuration generates `my.package.name.fragment.MyFragment` class.
But in 3.1.0, it generates `my.package.name.fragment.fragment.MyFragment` class.
I explicitly set `useSchemaPackageNameForFragments` to `true` in the `apollo` configuration, and this problem was solved.

In #3775, it says that the default value of `useSchemaPackageNameForFragments` is `true`, but it seems to be `false` by default.

Is this an intended behavior?

**Comment by martinbonnin** [comment]
You are 100% right, thanks for catching this. The default is false ([source code](https://github.com/apollographql/apollo-kotlin/blob/a1536a269ffe5896f1b5290e55bd361e2d398861/apollo-compiler/src/main/kotlin/com/apollographql/apollo3/compiler/Options.kt#L283)). 

This is more consistent with operations as fragments are not part of the schema but executable definitions. 

This is a source breaking change but I think it's acceptable since it requires rebuilding the code and code that is already shipped will keep working (transitive dependencies). Also doing this later will be even more complicated

In all cases, this deserves a lot more attention in the Changelog, I'll fix that now

**Comment by kubode** [comment]
Thank you for your quick response.
It's no problem 👍
