### ISSUE TITLE
`apolloStore.writeAndPublish(fragment` writes to previously written-to fragment of the same type

### ISSUE THREAD

**Issue by kroussevrb** [apollographql/apollo-kotlin#3875]
I have a Fragment 

```
data class ConversationFragment(
  val __typename: String = "Conversation",
  val id: String,
  val author: Author,
  val read: Boolean
) : GraphqlFragment {
```

for which I update some property (the value of `read`) this way:

```
client.apolloStore.writeAndPublish(
    fragment.copy(
      author = fragment.author.copy(fullName = author.unwrap(fragment.author.fullName)),
      read = read.unwrap(fragment.read),
    ),
    CacheKey.from(fragment.id),
    Operation.EMPTY_VARIABLES
  ).execute()
```

Then I perform the same thing for a different fragment with another author.

**Apollo updates the _previously updated_ fragment's `author` using the `author` of the second fragment.**

This breaks the same way if I use Apollo 3.1.0

I am currently working around it by replacing `node`s in the connection instead.

However, it makes me nervous as I have other situations in the codebase where I use `fragment`-based cache updates whose values' changing isn't that obvious (this one here changes the value of the author in a list) and I don't know what to expect.

This is the cache configuration, if it helps:

```
    val cacheFactory = LruNormalizedCacheFactory(EvictionPolicy.NO_EVICTION)
    val cacheKeyResolver = object : CacheKeyResolver() {
      override fun fromFieldArguments(field: ResponseField, variables: Operation.Variables) =
        cacheKey(field.resolveArgument("id", variables) as String?)
      override fun fromFieldRecordSet(field: ResponseField, recordSet: Map<String, Any>) =
        cacheKey(recordSet["id"] as String?)
      private fun cacheKey(value: String?) =
        when (value) {
          null, "" -> CacheKey.NO_KEY
          else     -> CacheKey.from(value)
        }
    }
```

**Comment by BoD** [comment]
Hi! Could the issue be that the `author`'s `fullName` is updated when you write the fragment, but since the cache works by referencing ids, that would also impact any other data referencing that particular author?

So for instance, before writing you had something like:

```
Author:A -> {id=A, fullName="John"}
Conversation:2 -> {id=2, read=false, author=CacheKey(Author:A)}
Conversation:1 -> {id=1, read=false, author=CacheKey(Author:A)}
```

and after, 

```
Author:A -> {id=A, fullName="NEW FULL NAME"}
Conversation:2 -> {id=2, read=false, author=CacheKey(Author:A)}
Conversation:1 -> {id=1, read=false, author=CacheKey(Author:A)}
```

Conversations 1 and 2 are impacted.

Sorry if I completely miss the mark here (I'm a bit new to the cache!) 😅

**Comment by kroussevrb** [comment]
You are right

I changed 

`author { fullName }`

to

`author { id fullName }`

and the problem went away!

What confused me is 
1. Why don't all of the fragments get updated and only ones I've previously written to for another reason even though all fragments are present in the cache
2. Didn't know we needed to include `id` in objects that we update manually and not automatically

Thanks

**Comment by martinbonnin** [comment]
Hi 👋  Sorry for the delay there. 

We have [this optimization](https://github.com/apollographql/apollo-kotlin/blob/eaf305bee5a96e7a7d73aa889d6ecfbc07a33a14/apollo-normalized-cache-api/src/commonMain/kotlin/com/apollographql/apollo3/cache/normalized/api/internal/Normalizer.kt#L75) to remove `QUERY_ROOT` from the cache keys to save a few bytes.

Unfortunately, this optimization is not checking for `QUERY_ROOT` and is also applied to your fragment root key here ("1" and "2"). Meaning that both authors are stored under cache key "author" while it should have been "1.author" and "2.author".

It's working when you're adding "id" in your query because it's using the author id instead of the field path for the cache key. This is certainly what you want to avoid data duplication so I'd recommend you keep "id" in as much as possible in your queries. Nevertheless, for cases where the path must be used as cache key this is a bug.

I'll make a fix for this. I think I'll just remove the optimization altogether and replace `QUERY_ROOT` with something simpler like `$` (TBC).

Thans for bringing this to our attention 🙏
