### ISSUE TITLE
ApolloDownloadSchemaTask throws "Apollo: no schema property" 

### ISSUE THREAD

**Issue by nevardreik** [apollographql/apollo-kotlin#3876]
**Summary**
My project implements `ApolloDownloadSchemaTask` for downloading our GraphQL schema, and then formatting it once downloaded. Since migrating to v3.1.0, this is now throwing the following:

```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':mobile-shared:downloadApolloSchema'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:188)
...
Caused by: java.lang.IllegalStateException: Apollo: no schema property
	at com.apollographql.apollo3.gradle.internal.ApolloDownloadSchemaTask.taskAction(ApolloDownloadSchemaTask.kt:81)
...
```

**Version**
3.1.0

**Description**
Here is my task (I have replaced my own domain with example.com - the real path provided exists and has been checked about 1000 times):
```
val updateGraphQlSchema by tasks.creating(ApolloDownloadSchemaTask::class) {
    val location = "src/commonMain/graphql/com/example/schema.json"

    schema.set(location)
    endpoint.set("https://example.com/graphql")

    // Prettify schema
    doLast {
        val schemaFile = File("$projectDir/$location")
        val prettySchema = groovy.json.JsonOutput.prettyPrint(schemaFile.readText(Charsets.UTF_8))
        schemaFile.writeText(prettySchema, Charsets.UTF_8)
    }
}
```

**Comment by BoD** [comment]
Hi 👋 !

I think this is because you should declare the task via `introspection` in the `apollo` block, as shown [here](https://www.apollographql.com/docs/kotlin/advanced/plugin-configuration/#downloading-a-schema). Then you should be able to add a `doLast` with something like:

```kotlin
tasks.withType(com.apollographql.apollo3.gradle.internal.ApolloDownloadSchemaTask::class.java) {
    doLast {
        // your custom code
    }
}
```

And then call `./gradlew downloadServiceApolloSchemaFromIntrospection`

By the way, did you know that if you use the `.graphqls` extension for the `schemaFile`, then the task will automatically convert the file to SDL format (which is nicer to use than json)?

**Comment by martinbonnin** [comment]
The issue is you're trying to use the general purpose `downloadApolloSchema` task and not the `updateGraphQlSchema` task that you defined.

Call `./gradlew updateGraphQlSchema` and it should work.

PS1: +1 for .graphqls schemas, that is much nicer to work with.
PS2: +1 for using the `introspection {}` block instead of relying on the task itself. The task can't be made internal for Gradle to instanciate it but it's not really meant to be used by user code as the wiring between tasks may change. I'd like in the future to hide the implementation of the Gradle plugin in another artifact (see [this issue](https://github.com/apollographql/apollo-kotlin/issues/1697)). It's still a long way so I don't expect `ApolloDownloadSchemaTask` to be removed in the near future but it might happen one day.

**Comment by martinbonnin** [comment]
@nevardreik anything else we can help with?
