### ISSUE TITLE
Handle scalar types with the same name but different case (e.g. "URL" and "Url")

### ISSUE THREAD

**Issue by hiltonc** [apollographql/apollo-kotlin#3880]
**Summary**
Scalar types with the same name but different case (e.g. "URL" and "Url") result in compilation errors in the generated code.

**Version**
3.1.0

**Description**
I have a schema using "scalar URL" in some places, "scalar Url" in others. I was able to register a custom scalar type for "URL" in v2 and it worked fine, but now in v3 I'm only getting a type generated for `URL` with compilation failures looking for type `Url`.

I realize I should just use the same case in all places, and I'm working with other teams in our org to fix this. Nevertheless it is a confusing error and a change in behavior.

**Comment by BoD** [comment]
Hi! 👋

Could it be that your system has a case insensitive file system (it's the default on MacOS for instance). In that case 2 generated files named `Url.kt` and `URL.kt` will end-up in the same file instead of 2.

**Comment by hiltonc** [comment]
@BoD Yes, I’m pretty sure that’s what is happening.

**Comment by BoD** [comment]
Thank you!

This could probably be detected/avoided in the code gen code. 

In the meantime as a temporary workaround, [it looks like](https://coderwall.com/p/mgi8ja/case-sensitive-git-in-mac-os-x-like-a-pro) it's possible on MacOS to create/mount a case-sensitive dmg file (I haven't tried! 😅)

**Comment by martinbonnin** [comment]
For the record, this happens in v3 because every type gets a top-level class with its name instead of adding enum values to a single class in v2. 

I'm not thrilled at the idea of adding code to detect case sensitivity in Apollo. That sounds like off topic for a GraphQL client. But maybe we can just put all scalar types in the same file? 

Until we settle on this, another workaround could be to rename the scalar in your schema. A simple search & replace should do it I think and be transparent to the backend

**Comment by hiltonc** [comment]
Yeah, I'm not sure if this is a problem Apollo should solve. I did find it confusing. Just wanted to surface it.

@martinbonnin Great suggestion, I have it working with a manual change while I wait for our actual schema to get updated.
