### ISSUE TITLE
Replacement for ApolloClient.builder's dispatcher?

### ISSUE THREAD

**Issue by alvindizon** [apollographql/apollo-kotlin#3940]
We are using version 2.5.11 and we have class we're using in unit tests that creates an ApolloClient, it uses a dispatcher like this:

```
ApolloClient.builder()
       .dispatcher(immediateExecutor())
```

Where immediateExecutor is
`private fun immediateExecutor(): Executor = Executor { command -> command.run() }`

What's the replacement for this in version 3?

**Comment by BoD** [comment]
Hi! Since v3 is now using coroutines under the hood there is no direct equivalent. A coroutine dispatcher can however be passed to `ApolloClient.Builder.requestedDispatcher` (and `asCoroutineDispatcher()` can be used to convert an Executor to a `CoroutineDispatcher`).

**Comment by martinbonnin** [comment]
I think what you're looking for here is [`Dispatchers.Unconfined`](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-dispatchers/-unconfined.html)

```kotlin
ApolloClient.Builder().requestedDispatcher(Dispatchers.Unconfined)
```

PS: we should revisit the naming there. It's named "requested" because this dispatcher is not honoured on native but we should change that when the new memory model lands.

**Comment by martinbonnin** [comment]
@alvindizon how did that go? Did that work?

**Comment by alvindizon** [comment]
Hi @martinbonnin , I haven't found the time to try @BoD and your suggestions yet, so I'll just close this issue for now. Thanks for your answers!
