### ISSUE TITLE
GraphQL Response No Longer Showing Up In Network Inspector In Android Studio

### ISSUE THREAD

**Issue by simon-the-canadian** [apollographql/apollo-kotlin#3962]
**Summary**
When looking at the network traffic in Android Studio using the Network Inspector tool the response is empty in the tool. The call does return data and everything loads fine in the app. I just can't view the network response in the Network Inspector tool.

**Version**
Apollo: 3.1.0
Android Studio: 2021.1.1

**Description**
If I revert to 3.0.0 then I can see the response and everything is fine. This only happens when I update to 3.1.0. I'm also on a MacBook running on Apple Silicone, if that makes a difference?

![Screen Shot 2022-03-24 at 6 00 47 PM](https://user-images.githubusercontent.com/17653830/160028984-4e0b4075-8307-4bd9-b682-63454600b10e.png)

**Comment by BoD** [comment]
Hi! 👋

Wow didn't know about this Android Studio feature, it is great! 😁

Doing a quick test on my side, I can't seem to reproduce (both using v3.0.0 and v3.1.0 work). One thing I notice is that selecting the first request in the timeline doesn't work though, wondering if maybe it's because it takes a while for the inspector to connect to the app. But the next ones work including the responses (see screenshots).

I'm also on Android Studio 2021.1.1 (Patch 2).

<img width="1671" alt="Screen Shot 2022-03-25 at 09 55 10" src="https://user-images.githubusercontent.com/372852/160088318-ec6e2bbb-401d-4e36-b106-fdc699ae9287.png">

<img width="1694" alt="Screen Shot 2022-03-25 at 09 55 23" src="https://user-images.githubusercontent.com/372852/160088338-910f2286-04ab-4079-bde8-d8f8a5e1ceb6.png">

The doc mentions it works with OkHttp - I don't think we touched that part of thc code between v3.0.0 and v3.1.0... So, not sure what the issue could be.

**Comment by martinbonnin** [comment]
The only change I can find that remotely touches HTTP is about query batching ([here](https://github.com/apollographql/apollo-kotlin/pull/3776)). 

This might very well be a tooling issue. If you can, can you dump the request/response using a 3rd party proxy like [Charles](https://www.charlesproxy.com/). That might give some hints what's going on

**Comment by simon-the-canadian** [comment]
It is a great tool 😄 
So after your comment, I decided to turn off batching to see what would happen. And it looks like its related because I can see the response in the tool after I removed `httpBatching` from my `ApolloClient.Builder`.

So when I have batching turned on `builder.httpBatching(maxBatchSize = 5)` the response is always empty in the tool. Even when its a single call in the request. And like I mentioned before, the app will handle the response and there is data. Just for some reason the Network Inspector isn't able to read it.

**Comment by martinbonnin** [comment]
That's interesting! Any chance you can dump the request headers with and without batching enabled?

**Comment by simon-the-canadian** [comment]
These are the headers for the request made without batching.

![Screen Shot 2022-03-25 at 9 27 00 AM](https://user-images.githubusercontent.com/17653830/160154494-4c65a575-2d7b-4c93-a62b-59e62f0829c2.png)

These are the headers for the request that uses batching

![Screen Shot 2022-03-25 at 9 37 03 AM](https://user-images.githubusercontent.com/17653830/160154688-4cffad24-b1a0-47f4-baab-a38feeec6f7c.png)

**Comment by martinbonnin** [comment]
Ah, looks like it's a `transfer-encoding: chunked` thing. Could it be this bug: https://issuetracker.google.com/issues/217765670?

Can you try with latest Dolphin Canary 5?

**Comment by simon-the-canadian** [comment]
Yeah I'll give that a try.

**Comment by simon-the-canadian** [comment]
I downloaded Canary 7 and its still broken.

**Comment by martinbonnin** [comment]
:/ Not sure there's anything we can do at this point. The headers looks ok to me. You could compare v3.0.0 vs v3.1.0 and see the difference in headers but even if there were something, I'm not sure we'd want to revert to v3.0.0.
