### ISSUE TITLE
Question about difference between v2 and v3 downloadApolloSchema gradle task

### ISSUE THREAD

**Issue by alvindizon** [apollographql/apollo-kotlin#4044]
We run the downloadApolloSchema in order to update our schema.json. In apollo graphql version v2 we do something like this:
```
./gradlew downloadApolloSchema --endpoint="https://api.mycompany.io/v2/graphql/" --schema="src/main/graphql/v2/schema.json" --variant release --service v2
```

In v3 apollo-kotlin, I understand that `--variant` and `--service` have been removed. I tried replacing them with `--graphVariant` and `--graph` respectively ~and it seems to work, but would like to know if this is correct.~

edit: just noticed that the output of the json file is different, it seems that the json file is not within a `data` field like this:

```json
{
  "data": { // everything should be within here }
}
```

I don't see this change and detailed info regarding the usage of downloadApolloSchema documented (the existing doc for this task doesn't describe in detail what purpose you'd use the different switches for), if it does can you point me to it? Thanks

**Comment by BoD** [comment]
Hi!

`--variant` has no equivalent in v3. Note that `--graphVariant` is unrelated to Android's variant, it is related to using Apollo Studio's schema registry. `--graph` is also related to the schema registry, so if I understand correctly that you are not using that, you should not need it either.

If you use different graphs per variants in Android, and/or different services, simply include that in the path of the destination.

Regarding `"data"` in the json file, I am not sure why there is a difference, but did you know that instead of the json format you can download the schema using the SDL format. Simply use the `.graphqls` extension in the destination file name instead of `.json`. I'd recommend it (unless you need the json format), as SDL is easier to read.

**Comment by martinbonnin** [comment]
Regarding "data", AFAIK, there's no official format for an introspection schema. Some tools expect the introspection result directly (including `"data"`), others unwrap this and just expect the list of types (without `"data"`). Historically, [Apollo Android has supported both](https://github.com/apollographql/apollo-kotlin/blob/c322f66497c7c88d1b14eefdbd60ac3faf6e44ca/apollo-compiler/src/main/kotlin/com/apollographql/apollo3/compiler/introspection/IntrospectionSchema.kt#L170) so it shouldn't matter whether `"data"` is present or not. But as @BoD mentions, `.graphql` is a way superior format so I'd recommend using that instead. [This blog post](https://www.apollographql.com/blog/frontend/sdl-support-in-apollo-android/) is a bit old but still relevant!

**Comment by alvindizon** [comment]
Thank you @BoD and @martinbonnin for the informative answers! We converted our schema to use the .graphqls format and it resulted in a greatly reduced size and it's more readable now 🎉
