### ISSUE TITLE
BearerTokenInterceptor on concurent requests? In KMM

### ISSUE THREAD

**Issue by boldijar** [apollographql/apollo-kotlin#4053]
I am using BearerTokenInterceptor class in our KMM project.

```
BearerTokenInterceptor(object : TokenProvider {
                                override suspend fun currentToken(): String {
                                    return authenticating.getCurrentJwtToken() ?: ""
                                }

                                override suspend fun refreshToken(previousToken: String): String {
                                    return refreshTokenHelper.refreshToken()
                                }
                            }),
```
And it works perfectly when we only fire one request, but when firing 2 requests at the same time, we have this issue, and we're unsure where is the problem, on the backend side, or on the client.

The code on android what will start the requests
```
  private fun startReq() {
        GlobalScope.launch {
            backend.....request1.execute() // some suspend function that does the apollo query
        }
        GlobalScope.launch {
            backend.....request2.execute() // same as above
        }
    }
```
    
   I see in the logs that both requests fire the same exact refresh token request, with the same refresh token, one is successful, one failes, because the refresh token is no longer valid (is one time use).
   
   I see in the source of the interceptor that it has some kotlinx.coroutines.sync.Mutex, is this supported for KMM ?
   
   Thank you!

**Comment by BoD** [comment]
Hi 👋  Thanks for reporting this!

I think this can be expected from the way it is implemented, 2 requests can still be executed in parallel with the same expired auth token, and will both result in `401`, and then will both call `refreshToken` - even if that part is guarded by the mutex, only one of them will succeed in your case.

I think what you could do is in your implementation of `TokenProvider.refreshToken()`, even if the refresh fails, still return the auth token - which should be valid at that point. 

This means you'll still have 2 `401` and 2 refreshes, only the first one will work, but both retries should work, and so that will be transparent to the caller.

Let me know if that makes sense.

**Comment by boldijar** [comment]
> Hi 👋 Thanks for reporting this!
> 
> I think this can be expected from the way it is implemented, 2 requests can still be executed in parallel with the same expired auth token, and will both result in `401`, and then will both call `refreshToken` - even if that part is guarded by the mutex, only one of them will succeed in your case.
> 
> I think what you could do is in your implementation of `TokenProvider.refreshToken()`, even if the refresh fails, still return the auth token - which should be valid at that point.
> 
> This means you'll still have 2 `401` and 2 refreshes, only the first one will work, but both retries should work, and so that will be transparent to the caller.
> 
> Let me know if that makes sense.

Very very interesting idea, I've added something like this, and what's even more interesting, is that now I can't reproduce the bug anymore, and it feels like the mutex is actually locking, maybe because I've added some extra variables to check if there's any current ongoing refresh? Or am I just going nuts

```
suspend fun refreshToken(): String {
    val ongoingRefresh = currentlyRefreshingToken
    currentlyRefreshingToken = true // added this global variable in this class
    logToConsole(text = "Attempting to refresh access token")
    val mutation = RefreshTokenMutation(refreshToken = getCurrentRefreshToken() ?: "")
    try {
        val response = apolloClient.mutation(mutation).executeOrThrowError()
        saveRefreshToken(response.authRefresh.refreshToken)
        saveJwtToken(response.authRefresh.accessToken)
        logToConsole(text = "Finished refreshing access token, auth overriding: $authOverriding")
        return response.authRefresh.accessToken
    } catch (e: Exception) {
        if (ongoingRefresh) {
            logToConsole(text = "We already refreshed this, so we just use the new token")
            return authenticating.getCurrentJwtToken() ?: throw Exception("Missing JWT token")
        }
        authenticating.logOutUser()
        throw e
    } finally {
        currentlyRefreshingToken = false
    }
}
```

**Comment by BoD** [comment]
I'm not 100% sure about the `ongoingRefresh` test but yes that was the idea. 

One thing we'd like to mention is that we'll probably deprecate `BearerTokenInterceptor` in the future, because as you have noticed, it is not well tested, and it looks like its implementation may be a bit too simplistic for most apps. It is good to keep as an example of an interceptor to deal with tokens, but we're not confident that it should really be used 'as is' in prod.

**Comment by martinbonnin** [comment]
[This PR](https://github.com/apollographql/apollo-kotlin/pull/4068/files#diff-d41aed3518f0ff5ad31ebd8ed44793c790fd53d7a1619d83fc8d505a82dc27cbR30) shows a more involved version of the `BearerTokenInterceptor`. Because there are so many possible implementations out there, we decided to deprecated `BearerTokenInterceptor` as it cannot work for all possible use cases out there. 

@boldijar looks like you got a working implementation on your side? Is it ok if I close this issue?

**Comment by martinbonnin** [comment]
@boldijar it's really hard to tell without more details of your server. What's more, this lib is more about GraphQL than the subtle oauth differences so things like authorization belong to somewhere else. `AuthorizationInterceptor` is a sample provided as inspiration but you should definitely test it/adapt it for your use case.

It looked like you had a working solution? If yes, I would keep it. Don't fix it if it ain't broke. If not then `AuthorizationInterceptor` is a good place to start looking.

**Comment by boldijar** [comment]
Yep, all good! Thank you
