### ISSUE TITLE
OkHttpExecutionContext replacement

### ISSUE THREAD

**Issue by denys-meloshyn** [apollographql/apollo-kotlin#4108]
**Question.**
`OkHttpExecutionContext` was available in version `2` after migration to `3.3.0` this context key was removed and I can't find another way how to get `okhttp` response from `ApolloResponse`

**Comment by martinbonnin** [comment]
Hi 👋 Thanks for reaching out

In 3.x you can use `response.executionContext[HttpInfo]`. That will give you the status code and headers from your HTTP call. If you need access to the body, I'd recommend using an [`HttpInterceptor`](https://www.apollographql.com/docs/kotlin/advanced/interceptors-http/) so that you can read the body as it is streamed. If you need something else, let us know and we can investigate together how to get it.

**Comment by denys-meloshyn** [comment]
thanks @martinbonnin for quick reply! The reason why I need `okhttp ` Response is because we have backend driven logic when automatically refresh page. 
This is an example how we did it previously.
```
apolloClient.query(...).rx().singleOrError().map {
            val okHttpResponse  = it.executionContext[OkHttpExecutionContext]?.response
            val maxAgeInSeconds = okHttpResponse?.cacheControl?.maxAgeSeconds ?: 0
        }
```

**Comment by martinbonnin** [comment]
I see, thanks for providing the details!

Looking at the [OkHttp code](https://github.com/1184893257/okhttp/blob/master/okhttp/src/main/java/com/squareup/okhttp/CacheControl.java#L220), looks like it's getting this value from a header so you could do something like:

```kotlin
    val maxAgeInSeconds = response.executionContext[HttpInfo]
        ?.headers
        ?.firstOrNull {
          it.name.lowercase() == "max-age"
        }
        ?.value
        ?.toIntOrNull()
```

Could that work?

**Comment by denys-meloshyn** [comment]
That's so neat! thank you for help and have a nice weekend 😊

**Comment by martinbonnin** [comment]
Thank you, you too :) !
