### ISSUE TITLE
Capitalized letters in schema fields - differences in v2 and v3

### ISSUE THREAD

**Issue by anderssandven** [apollographql/apollo-kotlin#4152]
Im using a Prisma based API which uses capitalized field names in types. V3 does not seem to like [this](https://github.com/apollographql/apollo-kotlin/blame/6216553fba26b560b2b11de73dcf963895e88e41/apollo-ast/src/main/kotlin/com/apollographql/apollo3/ast/internal/ExecutableValidationScope.kt#L141). I cant find any documentation on this and it seems like big change. It makes it very annoying to create queries when we have to alias all types. Are there any other ways to go about this?

**Comment by BoD** [comment]
Hi! Thanks for reporting this.

Indeed this was done because in the generated code, a class is generated for each composite fields, with the name of the field capitalized (`fooBar` -> `FooBar`). But if the field itself is named `FooBar` then there will be a conflict. 

This can be resolved with an alias but if your fields all are named with a capital letter this will be impractical indeed.

There is an option `flattenModels` to make the classes generated individually instead of nested, which avoid some clashes, but not all of them. I'm going to have a look at a way to fix the other clashes in the codeGen so this check can be disabled in conjunction with `flattenModels`.

**Comment by anderssandven** [comment]
That would be great. It probably save people some time if its mentioned in the migration guide as well ;)

**Comment by BoD** [comment]
A fix has just been merged where when using `flattenModels.set(true)`, capitalized fields names are accepted. The restriction still exists with nested models however.

This will be in the next release, in the meantime you can try it out with the [snapshots](https://github.com/apollographql/apollo-kotlin#snapshots).

**Comment by anderssandven** [comment]
Great job! Looking forward to testing it :)

**Comment by BoD** [comment]
Fix available in v3.3.1.
