### ISSUE TITLE
How to generate Query Classes with direct values in Constructor not as an Optional Types ?

### ISSUE THREAD

**Issue by RageshAntony** [apollographql/apollo-kotlin#4327]
### Question
Enter your question here.

Apollo KMM is generating Query Classes as Optional Types ..

```
public data class LoginUserQuery(
  public val phone_no: Optional<String?> = Optional.Absent,
  public val password: Optional<String?> = Optional.Absent,
.....
```

This makes me to call the constructor like 
`        LoginUserQuery(phone_no = Optional.presentIfNotNull("999999"),password = Optional.presentIfNotNull("ddd"))
`

I need something like 

        LoginUserQuery(phone_no = "999999",password = "ddd")

Is there any configuration to generate like above ?

**Comment by BoD** [comment]
Hi! 

If you declare your variables as non nullable (with `!`) they won't be generated as optional. Something like:

```graphql
query LoginUserQuery($phone_no: String!, $password: String!) {
```

**Comment by RageshAntony** [comment]
> Hi!
> 
> If you declare your variables as non nullable (with `!`) they won't be generated as optional. Something like:
> 
> ```graphql
> query LoginUserQuery($phone_no: String!, $password: String!) {
> ```

Yeah. Working Now. Thanks . 

But is there any way to do the same for nullable , like generating classes with default value constructs ..

public data class LoginUserQuery(
  public val phone_no: String? = null,
  public val password: String,
)

like this ?

**Comment by BoD** [comment]
You can define a default value on query arguments, like this:

```graphql
query LoginUserQuery($phone_no: String = null, $password: String!) {
```

this will generate something like:
```kotlin
public data class LoginUserQuery(
  public val phone_no: Optional<String?> = Optional.Absent,
  public val password: String,
)
```

Note, the reason `Optional` is generated by default is because a backend may distinguish:
- no value
- a present value which is `null`

If that's preferable, your can configure Apollo to generate a nullable type instead, by either adding `@optional(if: false)` on a specific argument, or globally with `generateOptionalOperationVariables.set(false)` - more info about this [here](https://www.apollographql.com/docs/kotlin/advanced/operation-variables). But note that if you use a default value as above, it will still be generated with `Optional`.

**Comment by RageshAntony** [comment]
@BoD .. Wow. This is what I expected. Thanks

**Comment by martinbonnin** [comment]
@RageshAntony do you mind if I close this one?

**Comment by RageshAntony** [comment]
No problem. Please proceed 😊
