### ISSUE TITLE
When use  nullableFieldStyle = JavaNullable.JAVA_OPTIONAL，generate two Optional;

### ISSUE THREAD

**Issue by doucheng** [apollographql/apollo-kotlin#4477]
### Summary
When use  nullableFieldStyle = JavaNullable.JAVA_OPTIONAL，generate two Optional;

generate:
```java
public class UpdateServiceUserCdpAttributeInput {

    public final Long userId;

    public final Optional<Optional<String>> jingpinAppLastActiveDate;

    public final Optional<Optional<String>> academicRecord;

    public final Optional<Optional<List<ServiceWeakSubject>>> weakSubject;
}
```
expected:
```java 
public class UpdateServiceUserCdpAttributeInput {

    public final Long userId;

    public final Optional<String> jingpinAppLastActiveDate;

    public final Optional<String> academicRecord;

    public final Optional<List<ServiceWeakSubject>> weakSubject;
}
```

### Version
3.7.0-SNAPSHOT

**Comment by martinbonnin** [comment]
Hi @doucheng ! 

Thanks for sending this. I know this is surprising but I believe this is the expected behaviour in order to be able to distinguish between:

* present and null
* present and non-null
* absent

This is especially important for mutation inputs:

```
mutation {
  # removes the address of user 42
  updateUser(input: {id:"42", address: null})
  # updates the name of user 42, leaves address untouched
  updateUser(input: {id:"42", name: "foo"})
}
```
We've turned this all around with @BoD and didn't find a more elegant solution to this problem. If you have other ideas, please let us know.

**Comment by doucheng** [comment]
Great Idea~
