### ISSUE TITLE
Why default fetch policy is CacheFirst?

### ISSUE THREAD

**Issue by Holoceo** [apollographql/apollo-kotlin#4497]
Why did you decide to use CacheFirst as default fetch policy?
For me it was not very obvious that after configuring ApolloClient with memory cache my queries started to behave differently.
It took me a while to notice this comment in documentation:
```
  // (Default) Check the cache, then only use the network if data isn't present
  .fetchPolicy(FetchPolicy.CacheFirst)
```

**Comment by martinbonnin** [comment]
Hi 👋 I'm not sure we have this decision documented somewhere but it kind of makes sense to me. If I add a cache, I'd like to use it by default. Note that you can change the client-wide behaviour by calling `fetchPolicy()` on the client builder instead of doing it for every call:

```kotlin
    val apolloClient = ApolloClient.Builder()
        .serverUrl(mockServer.url())
        .fetchPolicy(FetchPolicy.NetworkOnly)
        .build()
```

**Comment by martinbonnin** [comment]
Hi 👋 

> The method in the latest version of Apollo is httpFetchPolicy(), will it be changed to fetchPolicy()?

* `httpFetchPolicy` is for the HTTP cache
* `fetchPolicy` is for the normalized cache

Both methods will likely stay in the long term. Note that both of them are extension functions so they won't show up unless you add the matching dependency (`apollo-normalized-cache` or `apollo-http-cache`). The code paths are quite different but I think it makes sense for the default behaviours to match?

> However, this change was not obvious for us, we would have expected such important behavior change to be documented in the [migration guide](https://www.apollographql.com/docs/kotlin/migration/3.0/).

Yup, agree 100%. I'll take a look.

> We think it would be better to be able to override this default policy via a method in ApolloClient.Builder like defaultHttpFetchPolicy, what do you think?

`ApolloCall` and `ApolloClient.Builder` share the same configuration options through [`MutableExecutionOptions`](https://github.com/apollographql/apollo-kotlin/blob/2e0aaa4c0635e26deb2c192fa495f257abb420d5/libraries/apollo-api/src/commonMain/kotlin/com/apollographql/apollo3/api/ExecutionOptions.kt#L56). 

What's happening here is that `ApolloClient.Builder.httpFetchPolicy(FetchPolicy.NetworkOnly)` uses HTTP headers under the hood and these get overwritten by the call headers. I agree this is quite surprising. Currently there is no way to set default HTTP headers on `ApolloClient.Builder` and then "augment" them in `ApolloCall` because anything you set in `ApolloCall` will overwrite the default ones. Not 100% sure how to fix this but I'll take a stab at it. 

In the meantime, you could use your own function:

```kotlin

  fun <D: Operation.Data> ApolloCall<D>.addHttpHeadersWithDefault(headers: List<HttpHeader>): ApolloCall<D> {
    return httpFetchPolicy(HttpFetchPolicy.NetworkOnly).apply {
      headers.forEach {
        addHttpHeader(it.name, it.value)
      }
    }
  }
```

**Comment by Holoceo** [comment]
> Hi 👋 I'm not sure we have this decision documented somewhere but it kind of makes sense to me. If I add a cache, I'd like to use it by default. Note that you can change the client-wide behaviour by calling `fetchPolicy()` on the client builder instead of doing it for every call:
> 
> ```kotlin
>     val apolloClient = ApolloClient.Builder()
>         .serverUrl(mockServer.url())
>         .fetchPolicy(FetchPolicy.NetworkOnly)
>         .build()
> ```

Thanks Martin! Maybe it is worth mentioning it in `Normalized caches` section in docs.

**Comment by martinbonnin** [comment]
@Holoceo sure thing. Want to take a stab at it? Since you've bumped into it, you'll know best where to put the mention. No worries if you prefer me to do it, I'll find a place 😊. Up to you!

**Comment by juliagarrigos** [comment]
Thanks for the super quick answer @martinbonnin

> Not 100% sure how to fix this but I'll take a stab at it.

Keep us posted please 👍🏻 

> In the meantime, you could use your own function

Thanks for the suggestion!

**Comment by Holoceo** [comment]
> @Holoceo sure thing. Want to take a stab at it? Since you've bumped into it, you'll know best where to put the mention. No worries if you prefer me to do it, I'll find a place 😊. Up to you!

Sure. Happy to contribute.

**Comment by martinbonnin** [comment]
Many thanks @Holoceo for #4512 💙 ! Closing this now. Let me know if anything is still unclear.
