### ISSUE TITLE
Typename not always propagated on a union type when using `addTypename.set("always")`

### ISSUE THREAD

**Issue by agrosner** [apollographql/apollo-kotlin#4580]
### Summary

Given a graphql query like:
```graphql
query someQuery {
  someExperience {
    blocks {
      ...BBCollectionFragment
    }
  }
}

fragment BBCollectionDisplay on UnionTypeA {
  ... on GridDisplay {
    columns
  }
  ... on CarouselDisplay {
    itemsToShow
    rows
  }
}
fragment BBCollectionFragment on SomeType {
  blockId
  display {
    ...BBCollectionDisplay
  }
  mediumScreenDisplay {
    ...BBCollectionDisplay
  }
}

```
The resulting operationsOutput.json results in incorrect operations for `BBCollectionDisplay`. The type is a `UnionTypeA` (or `SomeType1 | SomeType2`). The output looks like:
```graphql
fragment BBCollectionDisplay on UnionTypeA {
  __typename
  ... on GridDisplay {
    columns
  }
  ... on CarouselDisplay {
    itemsToShow
    rows
  }
}

```

When we need:
```graphql
fragment BBCollectionDisplay on UnionTypeA {
  __typename
  ... on GridDisplay {
    __typename
    columns
  }
  ... on CarouselDisplay {
    __typename
    itemsToShow
    rows
  }
}

```

### Version

3.7.1

### Steps to reproduce the behavior

Create a query with a fragment on a union type. Place inline fragments in the query and observe that `__typename` are missing inside the inline fragments.

**Comment by martinbonnin** [comment]
Hi 👋 

> When we need:

```graphql
fragment BBCollectionDisplay on UnionTypeA {
  __typename
  ... on GridDisplay {
    __typename
    columns
  }
  ... on CarouselDisplay {
    __typename
    itemsToShow
    rows
  }
}
```

The codegen and parsers don't need `__typename` on inline fragments. Including it for the field is sufficient as all the other ones will be merged during execution. The only reason I can see for needing that is to be closer what `apollo client:push` is doing. Is that your case? If yes, you can use `./gradlew registerServiceApolloOperation` instead of `apollo client:push` and it will ensure that the queries are hashed consistently with the transformations that the codegen is applying. Or do you need theses `__typename` for another reason?

**Comment by martinbonnin** [comment]
Happy new year @agrosner 🎉 . Wish you all the best and lots of GraphQL fun for 2023! 

How can we move forward there? I'm reluctant to add yet another Gradle option if it's solely for `apollo client:push`. Can you share more about your use case?

**Comment by agrosner** [comment]
Thank you @martinbonnin ! We’ve tracked it down to actually our company internal tooling modifying the query itself, causing the mismatch. So I’ll close!

**Comment by agrosner** [comment]
Happy new year to you too!
