### ISSUE TITLE
1% Performance drop Apollo vs Retrofit

### ISSUE THREAD

**Issue by ynkm169** [apollographql/apollo-kotlin#4597]
### Question

Hello, 

**Background:**
We are migrating to GraphQL. This is what our code does:
1. user press a button
2. launch a new screen fragment with transition animation. At the same time, make a prefetch call to some API. In control group, we use Retrofit. In enabled group, we use Apollo.
3. the time it takes for the screen transition to finish is 1% longer in enabled group. 

**Issue investigation:**
A. I don't quite understand how would this GraphQL vs Retrofit affect screen transition. The prefetch call is a fire and forget that does not affect screen transition in anyway.
B. What I am suspecting is Apollo is doing some kind of work possible on the main thread. Since Android animation usually runs in main thread, maybe Apollo running code in main thread is causing this 1% drop of performance.
C. 2nd very wild theory is the worker thread Apollo is running on may be sharing the same core with main thread, hence the drop.
D. 3rd theory is we are using the default fetch policy, maybe it is checking Apollo store cache on main thread and takes some extra time? (In our Retrofit implementation, we check our own custom cache first. In our Apollo implementation, we rely on Apollo's cache).

**Question:**
What's the heaviest thing Apollo internally does? Like payload preparation, Json parsing, encrypting/encoding http traffic, runtime reflection or something else? Does Apollo do anything heavy on main thread?

**Comment by BoD** [comment]
Hi!

- [Request composition](https://github.com/apollographql/apollo-kotlin/blob/b925230bce99e5532fdebb194c5a7f5a7fa4a219/libraries/apollo-api/src/commonMain/kotlin/com/apollographql/apollo3/api/http/DefaultHttpRequestComposer.kt#L31) happens on the thread a query was executed (typically, the main thread)
- For anything network related Apollo uses OkHttp (same as Retrofit), and calls are executed on `Dispatchers.IO` [by default](https://github.com/apollographql/apollo-kotlin/blob/b925230bce99e5532fdebb194c5a7f5a7fa4a219/libraries/apollo-runtime/src/jvmMain/kotlin/com/apollographql/apollo3/internal/dispatchers.kt#L9)
- Json parsing also [happens](https://github.com/apollographql/apollo-kotlin/blob/b925230bce99e5532fdebb194c5a7f5a7fa4a219/libraries/apollo-runtime/src/commonMain/kotlin/com/apollographql/apollo3/network/http/HttpNetworkTransport.kt#L97) on `Dispatchers.IO`
- There is no runtime reflection in Apollo thanks to the code generation (unlike Retrofit)

(Not mentioning caching as I am guessing you are not using it for now.)

You may also find interesting information about threading in [this design doc](https://github.com/apollographql/apollo-kotlin/blob/main/design-docs/Threading.md) (but a warning that it may not be up to date as we have been trying to tweak things in [this PR](https://github.com/apollographql/apollo-kotlin/pull/4319/files?w=1)).

**Comment by ynkm169** [comment]
@BoD Thank you! That's very educative. 
For now, I will disable apollo cache with `.fetchPolicy(FetchPolicy.NetworkOnly)` and see if it helps speed up performance in our case.

**Comment by martinbonnin** [comment]
@ynkm169 you can also disable the cache completely (as in not calling `ApolloClient.Builder.normalizedCache()`) and it will save a few more CPU cycles. This skips an interceptor annd removes a few allocations and method calls. It's most likely very negligeable compared to network I/O but I'd thought I'd mention it for your experimentations.

As with everything there are multiple factors at play:

1. GraphQL POST data is typically larger than a REST call. You can look into [Automatic Persisted Queries](https://www.apollographql.com/docs/apollo-server/performance/apq/) to improve this
2. GraphQL merged fields require to buffer the Json stream which can introduce latency for some queries. You can look into [responseBased](https://www.apollographql.com/docs/kotlin/advanced/response-based-codegen/) codegen to improve this
3. Because GraphQL Json field order is deterministic, it opens up a few optimisation that make parsing potentially a bit faster (although I haven't been able to witness that just yet)
4. The time for your backend to process a REST vs GraphQL request might be different

Overall, we're aiming to be on par with Retrofit. And more importantly, we're aiming to do all processing/parsing amortized while waiting for network I/O. So the time it takes to do a query should be roughly the same as the time it takes to execute the network call. 

In these conditions, the most important contributors to any difference are be 1. and 4. which are outside Apollo Kotlin's control. 

I would consider 1% to be negligible at this point but if it's important to your use case, 2 way forward are:

1. Enable AutoPersistedQueries
2. Probe processing time on your backend for 2 equivalent queries
3. Look into `responseBased` codegen. This codegen comes with caveats and trade offs so I'd recommend you do that last as it'll require some time to setup correctly.

Hope this helps!

**Comment by ynkm169** [comment]
Thanks all! That's great amount of info for us to dig deeper into the performance difference! 
 I just added a bug ticket/feature request here https://github.com/apollographql/apollo-kotlin/issues/4604
