### ISSUE TITLE
Generate default arguments for `__typename`

### ISSUE THREAD

**Issue by chao2zhang** [apollographql/apollo-kotlin#4616]
### Use case

We are still migrating from Apollo 2 to Apollo 3. 
- `__typename` in the Apollo 3 code-generated data class does not seem to come with a default argument
- `__typename` in the Apollo 2 code-generated data class does come with a default argument

This is impacting the migration of an actual code base where there is at least 1k lines of unit test code that need to add `__typename = ` explicitly.

### Describe the solution you'd like

Generate the default argument

**Comment by chao2zhang** [comment]
Looks like "compat" mode is being removed in https://github.com/apollographql/apollo-kotlin/pull/4608/. So alternatively we need to use `DefaultApolloCompilerKotlinHooks` to orchestrate the behavior

**Comment by martinbonnin** [comment]
> `__typename` in the Apollo 3 code-generated data class does not seem to come with a default argument

That's correct. This is because we can't always know the `__typename`. For an example:

```graphql
interface Node

type Repository implements Node { 
  # fields
}

type User implements Node { 
  # fields
}
```

```graphql
query GetNode($id: ID!) {
  node(id: $id) {
    id
    # more fields
  }
}
```

The generated `Node` model could be of different concrete types  and therefore different `__typename` (`Repository` or `User` here). 

I'd recommend using [Data Builders](https://www.apollographql.com/docs/kotlin/testing/data-builders/) for this. In addition to being explicit about the `__typename`, it also handles merged fields much better:

```graphql
{
  node(id: 42) {
    ...Owner
    ...OwnerDetails
  }
}

fragment Owner on Repository {
  owner {
    id
  }
}
fragment OwnerDetails on Repository {
  owner {
    firstName
    email
  }
}
```

Using the models constructors, you'd have to create all fragments:

```kotlin
Data(
  node = Node(
    owner = Owner(id = 42),
    ownerDetails = OwnerDetails(firstName = "foo", email = "foo@bar.com")
  )
)
```

vs the Data builders match the Json:

```
Data {
  node = buildUser {
    id = 42
    firstName = "foo"
    email = "foo@bar.com"
  }
}
```

CompilerHooks could work but data builders will certainly be more future proof (they also allow faking some values)

**Comment by chao2zhang** [comment]
👍  I think we can close this issue as the implementation of the compiler hook only makes sense for the repo I am working on.

A remaining question to confirm: If giving a default argument to `__typename` to assist the migration (especially unit tests), the production code execution shouldn't be impacted as the `__typename` would always be parsed from the server response.

**Comment by martinbonnin** [comment]
>  If giving a default argument to __typename to assist the migration (especially unit tests), the production code execution shouldn't be impacted as the __typename would always be parsed from the server response.

Correct.
