### ISSUE TITLE
Allow modifying existing service created ahead of time by a convention plugin

### ISSUE THREAD

**Issue by scana** [apollographql/apollo-kotlin#4720]
### Use case

Given this setup:
```groovy
// project/build-conventions/src/main/groovy/company.apollo.plugin
plugins {
  id 'com.apollographql.apollo3'
}

apollo {
  def namespace = somePackageName // e.g. generated by module name -> com.company.feature1 for module named feature 1
  service(namespace) {
    packageName.set(namespace)
    addTypename = "always"
  }
}
```
```groovy
// project/modules/feature1/build.gradle

plugins {
  id 'company.apollo'
}

apollo {
  service("com.company.feature1") {
      generateTestBuilders = true
  }
}
```

The sync/build will fail as there is already a service named `com.company.feature1` created.
I would like to be able to have a set of default settings for every module to share, but still allow some modules to modify those settings however they like.

### Describe the solution you'd like

I'd like to have an ability to modify existing service.

I understand that removing build error when duplicate service is being created is error-prone so perhaps this could be a separate API, like `onService(name, action)`, `modifyService(name, action)`?

**Comment by martinbonnin** [comment]
Hi! Thanks for opening this. This is in fact something I wanted to do, there might even be a `declarative-service` branch lying around but decided not to do ultimately because:

1. It doesn't play well with the current `outputDirConnection {}` API. This API is responsible for wiring the Apollo and Kotlin compilers and this is done at service (and therefore task) creation. I'm not sure of an easy way to postpone this while still allowing to provide a default wiring (without relying on `afterEvaluate {}` and the likes)
2. More generally I like the idea that there's a single place that configures the Apollo compiler. I've been bitten way too many times in Gradle when a property changed too late or too early and it wasn't clear what part of the build contributed what property.

My recommendation would be to wrap the Apollo plugin in your convention plugin:

```kotlin
plugins {
  id 'company.apollo'
}

company {
  apolloService("com.company.feature1") {
    # `this` is not ApolloExtension here but some extension specific to your convention plugin
    generateTestBuilders = true     
  }
}
```

I believe there might even be benefits to this approach as you can restrict what can/cannot be overriden is specific modules. For an example, you can enforce that `allWarningsAsErrors` is true or any other thing.

I know this is not typically what Gradle does and prefers things like `NamedDomainObjectCollection`... This is not a hill I want to die on so if there are strong opinions about changing this we can revisit but at least I would try the delegation way if you can? 
Let me know what you think!

**Comment by scana** [comment]
Hey @martinbonnin thank you for such a quick reply!
I really like the idea behind better control of what can be modified that you proposed.

I assumed this would work but maybe I'm missing something? Not sure if I can even achieve to wrap a plugin without writing regular plugin class in Groovy/Kotlin?

```groovy
// project/build-conventions/src/main/groovy/company.apollo.plugin
plugins {
  id 'com.apollographql.apollo3'
}

interface CompanyApolloExtension {
  Property<Boolean> getGenerateTestBuilders()
}

def extension = project.extensions.create("companyApollo", CompanyApolloExtension.class)

apollo {
  def namespace = somePackageName // e.g. generated by module name -> com.company.feature1 for module named feature 1
  service("service") {
    packageName.set(namespace)
    // set it to false by default
    extension.generateTestBuilders.convention(false) 
    // lazily resolve the value
    generateTestBuilders.set(extensions.generateTestBuilders) 
  }
}

// project/modules/feature1/build.gradle

plugins {
  id 'company.apollo'
}

companyApollo {
  generateTestBuilders.set(true)
}
```

**Comment by martinbonnin** [comment]
Correct, that's one thing with Gradle extensions is that you need to have one level of nesting to have it actually "execute" code (vs just setting properties). My Groovy is a bit rusty but the idea is something like this:

```groovy
// project/build-conventions/src/main/groovy/company.apollo.plugin
plugins {
  id 'com.apollographql.apollo3'
}

interface ApolloParams {
  Property<Boolean> getGenerateTestBuilders()
}

abstract class CompanyApolloExtension {
  void configure(closure: Closure<ApolloParams>) {
    let params = objects.create(ApolloParams::class)
    closure(params)
    apollo {
    def namespace = somePackageName // e.g. generated by module name -> com.company.feature1 for module named feature 1
    service("service") {
      packageName.set(namespace)
      // no need to do things lazily, it's all done once
      extension.generateTestBuilders.convention(params.generateTestBuilders.orElse(false)) 
    }
  }
  }
}

def extension = project.extensions.create("companyApollo", CompanyApolloExtension.class)



// project/modules/feature1/build.gradle

plugins {
  id 'company.apollo'
}

companyApollo {
  configure {
    // does not do anything because apollo is already applied at this time
    generateTestBuilders.set(true)
  }
}
```

I'll update this response if I get a chance to try it out on a real Groovy project but wanted to get it out to give the general idea. Then your build script becomes the single place that triggers the creation of the Apollo tasks (even if the actual logic is inside your convention plugin).

**Comment by scana** [comment]
Thanks! I really appreciate you spending time on this 🙏 

I ended up with:
```groovy
plugins {
  id 'com.apollographql.apollo3'
}

interface ApolloParams {
  Property<Boolean> getGenerateTestBuilders()
  Property<Boolean> getGenerateApolloMetadata()
  Property<Boolean> getGenerateFragmentImplementations()
  Property<String> getAddTypename()
}

abstract class CompanyApolloExtension {

  private final Project project

  CompanyApolloExtension(Project project) {
    this.project = project
  }

  void configure(Action<ApolloParams> configBlock) {
    def params = project.objects.newInstance(ApolloParams.class)
    configBlock.execute(params)
    def apollo = project.extensions.getByName("apollo")
    apollo.service("service") {
      def namespace = project.ext["generatedNamespace"]
      packageName.set(namespace)
      generateTestBuilders.set(params.generateTestBuilders.orElse(false))
      generateApolloMetadata.set(params.generateApolloMetadata.orElse(false))
      generateFragmentImplementations.set(params.generateFragmentImplementations.orElse(false))
      addTypename.set(params.addTypename.orElse("ifFragments"))
    }
  }
}

project.extensions.create("companyApollo", CompanyApolloExtension.class, project)

dependencies {
  apolloMetadata(projects.modules.network.core)
}
```

and then this seems to work:
```groovy
companyApollo {
  configure {
    generateFragmentImplementations.set(true)
  }
}
```
---

> Then your **build script becomes the single place that triggers the creation of the Apollo** tasks (even if the actual logic is inside your convention plugin)

Now the only thing to figure out is how to make it as easy to add to a module as possible - I assume that reconfiguring Apollo would be done only in few places.
Right now every module using this plugin has to add:
```groovy
companyApollo {
  configure {
    // empty statement just to initialise Apollo plugin
  }
}
```

**Comment by martinbonnin** [comment]
> Thanks! I really appreciate you spending time on this 🙏

Ah perfect! yea, that's way better than my attempt :)!

> Now the only thing to figure out is how to make it as easy to add to a module as possible

Gosh you're right. Always that default behaviour coming back at us... Unfortunately I don't have an easy answer for that except going for `afterEvaluate {}` which is not realliy great... 

You could make it look slightly better like this:

```groovy
```

So another solution would be going back

**Comment by martinbonnin** [comment]
(sorry pressed enter too fast)

A few other things: `getGenerateTestBuilders` is actually a special case because it's used at task "configuration" time ([here](https://github.com/apollographql/apollo-kotlin/blob/f6cbc453e8728a9ad576e6635fa329b18849cd39/libraries/apollo-gradle-plugin-external/src/main/kotlin/com/apollographql/apollo3/gradle/internal/DefaultApolloExtension.kt#L410)) while something else like `generateFragmentImplementations` is only used at "execution" time ([here](https://github.com/apollographql/apollo-kotlin/blob/8277227b5d7866311fb8d36c73ad2237b3c471fb/libraries/apollo-gradle-plugin-external/src/main/kotlin/com/apollographql/apollo3/gradle/internal/ApolloGenerateSourcesTask.kt#L350)). 

I believe this is actually the real reason why your [first version above](https://github.com/apollographql/apollo-kotlin/issues/4720#issuecomment-1452490808) didn't work. Other parameters should be resolved lazily from the task action but `getGenerateTestBuilders` is "special" because used directly from `service(foo)` to wire the sources to the test source set. 

This goes deep into workaround land but one solution might be to unconditionally wire the test source set while not always generating the source files:

```groovy
// project/build-conventions/src/main/groovy/company.apollo.plugin
plugins {
  id 'com.apollographql.apollo3'
}

interface CompanyApolloExtension {
  Property<Boolean> getGenerateTestBuilders()
}

def extension = project.extensions.create("companyApollo", CompanyApolloExtension.class)

// During configuration, wire the test source set
extension.generateTestBuilders.set(true)

apollo {
  def namespace = somePackageName // e.g. generated by module name -> com.company.feature1 for module named feature 1
  // Create the service and wire everything
  service("service") {
    packageName.set(namespace)
    // set it to false by default
    extension.generateTestBuilders.convention(false) 
    // lazily resolve the value it will resolve to true while in the `apollo {}` block
    generateTestBuilders.set(extensions.generateTestBuilders) 
  }
}

// Configuration is finished, default to false again and leave each project decide to opt-in actual model generation
extension.generateTestBuilders.set(false)

// project/modules/feature1/build.gradle
plugins {
  id 'company.apollo'
}

companyApollo {
  generateTestBuilders.set(true)
}
```

**Comment by scana** [comment]
Wow - thank you once again @martinbonnin, I confirm this works great! I would probably never return to original solution without your input ❤️ 

This allowed us to keep the config in check and to migrate from:
```
apollo {
   ...
}
```
to:
```
apollo {
   service("service") {

   }
}
```

This is perhaps a case for a different GitHub issue but after switching we've observed that `kapt` would generate java stubs in test sources for all generated Apollo classes - going back to default "service" runs fine 🤔

**Comment by martinbonnin** [comment]
Nice, glad to hear it worked! 

> `kapt` would generate java stubs in test sources for all generated Apollo classes - going back to default "service" runs fine

Interesting... How much of a problem is this? Sounds to me that generating kapt stubs should be the intended behaviour if you have kapt enabled in your build?

**Comment by scana** [comment]
Well normally we would not observe this because kapt would not touch generated sources for some reason.
The thing is that we only run this for tests as regular builds are taken care of by [Anvil](https://github.com/square/anvil).

I was just wondering whether anything has changed regarding source sets - our config stays virtually the same, the only thing that we've changed was to add explicit service declaration.

An example which causes the build to fail (this might also be an issue of the way our GraphQL schema is structured, but still, it works fine without `kapt`).
This is also related to generating fragment implementations.
```
> Task :modules:feed:kaptDebugUnitTestKotlin FAILED
/Users/scana/company/modules/feed-v3/build/tmp/kapt3/stubs/debugUnitTest/company/feed/fragment/FeedImpl.java:747: error: repeated interface
                    public static final class Feed implements company.feed.fragment.Section.Feed, company.feed.fragment.Feed.Sections.Edge.Node.Feed {
```

**Comment by martinbonnin** [comment]
> I was just wondering whether anything has changed regarding source sets - our config stays virtually the same, the only thing that we've changed was to add explicit service declaration.

The thing that changed is that the default service was registered from `afterEvaluate {}` so _maybe_ that was late enough that AGP didn't add it to the kapt task or something like this. This is exactly the kind of hard problem that are hard to diagnose with `afterEvaluate {}` and why I'd like to remove the default service.

It happens to [break your workflow](https://xkcd.com/1172/) but in the grand scheme of things, it might (or might not be) completely illogical for `kapt` to run on test sources as well. Would you have a reproducer somewhere? I can double check.

```
public static final class Feed implements company.feed.fragment.Section.Feed, company.feed.fragment.Feed.Sections.Edge.Node.Feed
```

You bumped into https://youtrack.jetbrains.com/issue/KT-24272. One workaround for this is to use `flattenModels.set(true)`:


```kotlin
apollo {
  flattenModels.set(true)
}
```

Or otherwise, you can move your GraphQL files to a separate module that doesn't apply `kapt`.

**Comment by scana** [comment]
> The thing that changed is that the default service was registered from afterEvaluate {} so maybe that was late enough that AGP didn't add it to the kapt task or something like this

Ok - that makes perfect sense. I don't have a repo to reproduce this very moment unfortunately. I think we've just been sitting on a ticking time bomb without awareness of it. 
I will give it a try with `flattenModels` option - however our codegen is `responseBased` - is there anything that we should be aware of?

@martinbonnin I cannot thank you enough for your help 😄

**Comment by martinbonnin** [comment]
> I will give it a try with flattenModels option - however our codegen is responseBased - is there anything that we should be aware of?

That will most likely create huge amounts of suffixed classes (`Feed1`, `Feed2`, etc...). All in all, for `responseBased` codegen, I'd personnaly go with a separate module that doesn't involve `kapt`. I'm actually curious why this wasn't an issue on your `main` models, this tends to happen quite a lot.

> @martinbonnin I cannot thank you enough for your help 😄

Sire thing. Sorry this is all complicated. Once anvil supports KSP and you can remove kapt, it should be a bit more simple

**Comment by martinbonnin** [comment]
Some end of the week thoughts here. Did you end up with a working setup? 

If yes, then it's all good 👍 . 
If not, would you consider switching from `responseBased` to `operationBased`? Sure it doesn't have all the type information of `responseBased` but that extra verbosity (to put `.fooFragment` everywhere) pays in terms of maintainability.  Just my 2 cents here, let me know if I can help with anything else.

**Comment by scana** [comment]
Hey @martinbonnin - yeah my setup is now working fine - thank you for your help and all of your hard work on `apollo-kotlin` 🙏 

Have not decided yet whether we want to have a separate module - ideally I would just get rid of `kapt` altogether. Will do some research whether it's possible to exclude classes from stub generation in my free time.

**Comment by martinbonnin** [comment]
Thanks for the update!
