### ISSUE TITLE
External interfaces for JS interop

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-kotlin#4732]
### Use case

This is a follow up from https://github.com/apollographql/apollo-kotlin/issues/4728

To provide JS interop in the case of a response in the form of a JS object,  generate [external interfaces](https://kotlinlang.org/docs/js-interop.html#external-interfaces) that could describe the shape of the response.

**Comment by martinbonnin** [comment]
@baconz initial implementation is there: https://github.com/apollosolutions/apollo-jsei. It's barebones but it's working for my simple test cases. Feel free to hit it with a hammer and report bugs/missing features!

**Comment by baconz** [comment]
This is so cool! I'm going to try to mess around with it a bit later in the week -- probably Wednesday-ish.

**Comment by baconz** [comment]
I tried it in the repro project that I made, but I wasn't able to get it working. I think I might be missing something obvious, though.

One thing I noticed is that the README has the wrong path for the plugin, I think it should be `com.apollographql.jsei`.

I'm getting this exception:

```
Caused by: java.lang.NoSuchMethodError: 'java.lang.Object com.apollographql.apollo3.ast.GQLResult.getOrThrow()'
	at apollo.jsei.internal.codegen.ApolloJseiCompiler.compile(ApolloJseiCompiler.kt:26)
```

The code is up on a branch here: https://github.com/baconz/apollo-kotlin-js-performance/pull/1

@martinbonnin could you take a look?

**Comment by martinbonnin** [comment]
> I think it should be com.apollographql.jsei.

Good catch, [fixed](https://github.com/apollosolutions/apollo-jsei/commit/d0094f249cb92ec82bf024eafd644532e8fc131b)

> Caused by: java.lang.NoSuchMethodError: 'java.lang.Object com.apollographql.apollo3.ast.GQLResult.getOrThrow()'

This was dependent on [this PR](https://github.com/apollographql/apollo-kotlin/pull/4737) that isn't merged yet. I just pushed a new SNAPSHOT.

**Comment by martinbonnin** [comment]
[Snapshots are now published automatically](https://github.com/apollosolutions/apollo-jsei/actions/runs/4354807486/jobs/7610572668) so it shouldn't happen again (or at least we'll notice if it happens :) ). Sorry again for that!

**Comment by baconz** [comment]
I got it working! For some reason it looks like the snapshot still has the old version, though? I ended up using a `mavenLocal` version.

A few comments from first impressions:

1. I think we need to use `Array` instead of `List`. The JS client returns `Array`s, and Kotlin will not treat them as `List` so we get a `TypeError` with the current implementation.
2. It would be nice to generate the top level `Response` object as well. Right now, I have manually created something like:
```kotlin
external interface AllFilmsQueryResponse {
    val data: AllFilmsQueryData?
    val errors: Array<Any>?
}
```
3. This one is a bit more pie-in-the-sky, but it would be really cool to generate an extension function capable of translating the JSEI to a normal apollo-kotlin response. I think that would probably require a level of coupling that doesn't exist today, but it would be make using this library very convenient.

I pushed my latest to the same branch referenced above if you want to have a look.

**Comment by martinbonnin** [comment]
> For some reason it looks like the snapshot still has the old version, though? 

Gosh 🤦 . Sorry about this. Will double check.

> I think we need to use Array instead of List. The JS client returns Arrays, and Kotlin will not treat them as List so we get a TypeError with the current implementation.

Ah good catch! 

> It would be nice to generate the top level Response object as well.

Agreed 👍 

> This one is a bit more pie-in-the-sky, but it would be really cool to generate an extension function capable of translating the JSEI to a normal apollo-kotlin response.

At some point it feels like this is re-doing the work that the generated adapters are doing already and feels like it should be identically slow (or fast)... Or maybe we're saying that parsing is slow because it works on a byte by byte basis and it would be much faster to have it work on the full JS object in memory all at once? In which case we wouldn't need JSEI anymore but more  something like this:

```kotlin
val response = operation.parseFromJsObject(obj)
```

?

**Comment by martinbonnin** [comment]
There's the [JsonReader API](https://github.com/apollographql/apollo-kotlin/blob/05f2a3295517fb7a64c2259c38b453a37f3c4d19/libraries/apollo-api/src/commonMain/kotlin/com/apollographql/apollo3/api/json/JsonReader.kt#L40) that is relatively self-contained and could be changed to read from JSObjects instead of a `BufferedSource`. There's already [one that reads from a `Map`](https://github.com/apollographql/apollo-kotlin/blob/05f2a3295517fb7a64c2259c38b453a37f3c4d19/libraries/apollo-api/src/commonMain/kotlin/com/apollographql/apollo3/api/json/MapJsonReader.kt#L31) so the same logic could work with JS objects.

**Comment by baconz** [comment]
Ah, got it. Didn't realize that was possible. That is really cool! So it would be a matter of writing one of those that takes a `dynamic`, or perhaps wrapping the `dynamic` in a `Map` interface.

The trouble is going to be [here](https://github.com/apollographql/apollo-kotlin/blob/05f2a3295517fb7a64c2259c38b453a37f3c4d19/libraries/apollo-api/src/commonMain/kotlin/com/apollographql/apollo3/api/json/MapJsonReader.kt#L22) and [here](https://github.com/apollographql/apollo-kotlin/blob/05f2a3295517fb7a64c2259c38b453a37f3c4d19/libraries/apollo-api/src/commonMain/kotlin/com/apollographql/apollo3/api/json/MapJsonReader.kt#L21) since the `dynamic` will expose other `dynamic`s or `Array`s but not `Map`/`List`.

**Comment by martinbonnin** [comment]
[Arrays](https://github.com/apollosolutions/apollo-jsei/commit/65fe5e0a8df5e4eecfab735fbdb643905f8fa516) and [Response models](https://github.com/apollosolutions/apollo-jsei/commit/65fe5e0a8df5e4eecfab735fbdb643905f8fa516) are pushed to the repo and [recent snapshots showed up](https://s01.oss.sonatype.org/content/repositories/snapshots/com/apollographql/jsei/apollo-jsei/0.0.1-SNAPSHOT/) 🤞 so this part should be good 🤞 

Do you want to look into `DynamicJsonReader` ? Feel free to send a PR if you feel like it but no obligation at all, I'll can also look at it later this week.

**Comment by baconz** [comment]
I can take a stab at it, but probably won't have a chance until Friday-ish.

**Comment by martinbonnin** [comment]
Nice! Let me know how that goes! 

PS: If you want to discuss in a more unformal place than GitHub issue, you can also join #apollo-kotlin on the [Kotlin slack](https://slack.kotlinlang.org)

**Comment by martinbonnin** [comment]
There is now:

* `DynamicJsJsonParser`: https://github.com/apollographql/apollo-kotlin/pull/4750
* `apollo-jsei`: https://github.com/apollosolutions/apollo-jsei

I'm closing this issue, let's follow up in more focused ones if needed.
