### ISSUE TITLE
With more than one subscription and network off for long duration, webSocketReopenWhen can take unexpectedly long to establish connection when network is back on. 

### ISSUE THREAD

**Issue by parijat-shah** [apollographql/apollo-kotlin#4805]
### Version

3.7.4

### Summary

```
if (reopenWhen?.invoke(message.cause, reopenAttemptCount) == true) {
              reopenAttemptCount++
              activeMessages.values.forEach {
                // Re-queue all start messages
                // This will restart the websocket
                messages.trySend(it)
              }
            }
```
       
In the WebSocketNetworkTransport, the above code and quickly add to the messages queue if network is off for the longer time and there are more than one subscriptions i.e activeMessage size is > 1 

lets consider 5 subscriptions i.e activeMessage.size = 5 

when if ( reopenWhen?.invoke ... ) conditions evaluates to be true, 
The code runs for 5 times since activeMessage size is 5 , the message type `Command` is sent.   \\messages.trySend(it)
At this point, the message queue will have :  Command,Command,Command,Command,Command

Each of these messages will be handled in `Command` block by creating protocol and trying to initialize connection. Since network is still off , network exception is thrown 

messages.send(NetworkError(e))

After all Command messages in the queue are executed, the queue will now have 5 events each of type `Network Error` or NE

NE, NE, NE, NE, NE

Each of this will result in reopenWhen?. suspending for 60 seconds, but after total 3 minutes , the queue will have
Command, Command ...... Command ( total 25 messages )
Each of this command will result in again one exception since network is still off. 
The queue will have
NE,NE,NE .... NE ( 25 message )
Now for each NE, you will wait 60 seconds and go through activeMessages loop, resulting in
Command, Command ..... Command ( total 125 message )
If network is still off , this will result in
NE, NE .. NE ( 125 message )

At this point if network is back on, it will require 2+ hours to process all of 125 message of type Event ( Network Error ) before 
a message of type `Command` can be processed. 

There seems to be a problem in which the messages are queued. 

### Steps to reproduce the behavior

Start more than one subscriptions ( More subscription soon you will run into it )
use webSocketReopenWhen option when you create ApolloClient ( short delay will result in messages queue increasing quickly)

Turn off network for extended period of time and you will notice the messages size growing.
Turn back on the network and it will some time before, connection is established.  

### Logs

```
(Your logs here)
```

**Comment by baconz** [comment]
I just want to highlight the importance of this bug. I think that right now the semantics of the API make it deceivingly easy to end up with an exponentially increasing wait time, and a websocket that is effectively useless.

I think the solution is probably to rework the state machine so that we only retry once per connection attempt, and we only start up the operations once there is a successful connection.

**Comment by CureleaAndrei** [comment]
Facing the same issue. Looking forward to an answer.

**Comment by martinbonnin** [comment]
@parijat-shah this should be fixed thanks to the awesomeness of @baconz ! Can you give a try at 3.8.2 and let us know how that works for you?

**Comment by martinbonnin** [comment]
I'm going to assume this worked. Please leave a comment if you're still having the issue.

**Comment by rmberg** [comment]
@martinbonnin let me know if it would be more helpful to open a separate issue for this:  

I was doing some testing on how subscriptions behave when the server is or becomes unreachable (due to network connectivity issues, server being down, etc..). I have a `reopenWhen` implemented as so:

```kotlin
.reopenWhen { _, attempt ->

                       println("Attempt: $attempt")
                        delay(2.0.pow(attempt.toDouble()).toLong())

                        // retry after the delay
                        true
                    }
```

With 3.8.1 I noticed that if the server is currently unreachable, and I attempt to establish a new subscription, the retry runs once with the output "Attempt: 0", and would never retry again.

After upgrading to 3.8.2 if the server is unreachable when trying to establish the subscription it does retry as expected. However once the server becomes available while the client is re-trying, the subscription is established, but no messages are ever received at that point.

Could there be an issue with the subscription being established after the `reopenWhen` attempt succeeds?

Thank you,
Ryan
