### ISSUE TITLE
Migration for adding withDates parameter to sqliteNormalizedCache

### ISSUE THREAD

**Issue by colintheshots** [apollographql/apollo-kotlin#5026]
### Use case

Currently, adding the `withDates=true` parameter to a new release does not perform any migration. Instead, the first query crashes with the following error. It seems preferable to offer either a destructive migration option or an SQlite table migration. Since this table is used only for caching, a destructive migration often makes sense here.

```
java.lang.IllegalStateException: Apollo: Cannot find the 'blobs' table, did you change the 'withDates' parameter? (found '[android_metadata, records, sqlite_sequence]' instead)
```

### Describe the solution you'd like

I believe there should be a migration to explicitly add the missing dates column, either destructive or automated. Currently, `maybeCreateOrMigrateSchema` is a no-op for the normalized SQlite cache. Also, there is no versioning for the database, which could assist in performing either type of migration.

**Comment by martinbonnin** [comment]
Hi ! 

Indeed, it's not possible to change that parameter during the life of an app at the moment using `apollo-normalized-cache-incubating` artifacts. The `blobs` and `records` tables are quite different. Adding `withDates` stores data in a binary `blob` while the default format in the `records` table is JSON strings. This is so that the new format stores data more efficiently, especially when there are a lot of redundant date information. This is still incubating and that binary format will most likely still change, I wouldn't use this in production.

Migrations will come but only once that format is stabilized. If you really want to test both, you can use different DB names to avoid crashing.

**Comment by colintheshots-meetup** [comment]
I'll give that a try, thanks.

We were using the normalized cache alongside the http cache, which was confusing engineers because they thought the http cache expirations would apply to the normalized cache as well. Data was getting cached eternally, unlike Apollo 2.

**Comment by martinbonnin** [comment]
Expiration is a pretty complex issue with the normalized cache because of overlapping queries, etc... Unlike HTTP, there is no 1:1 correspondance between a cache entry and an operation hence all the `withDates` stuff. It's still wildly experimental though so wouldn't use it in production. If you really need to keep your normalized cache under control, you can periodically clear it. It's not great but it works.

**Comment by martinbonnin** [comment]
I'm going to close this one cause it's not actionable until the `apollo-normalized-cache-incubating` reaches an higher level of maturity
