### ISSUE TITLE
Is it possible to distinguish between waiting times for a network response and a cache hit?

### ISSUE THREAD

**Issue by sonatard** [apollographql/apollo-kotlin#5073]
### Question

Is there a way to distinguish whether I'm waiting for a network response or waiting for the result of a cache hit?

I want to display a Spinner as a loading indicator while waiting for a network response, but I don't want to display it in the case of a cache hit because it flickers.

**Comment by martinbonnin** [comment]
Excellent question!

If you're using `4.0.0-alpha.2`, the Flow emits cache misses so you can rely on the order of emissions to display the loading state only once you get a cache miss. Something like so:

```kotlin
    val flow = remember {
        apolloClient.query(LaunchDetailsQuery(launchId))
            .fetchPolicy(FetchPolicy.CacheFirst)
            .toFlow()
            .map {
                when {
                    it.data != null -> Success(it.data!!)
                    // only display the loading view once you get a cache miss 
                    it.exception is CacheMissException -> Loading
                    else -> Error(it.exception)
                }
            }
    }
    val state by flow.collectAsStateWithLifecycle(LaunchDetailsState.Initial)

    when (val s = state) {
        is LaunchDetailsState.Initial -> EmptyView()
        is LaunchDetailsState.Loading -> LoadingView()
        is LaunchDetailsState.Success -> SuccessView(s.data)
        is LaunchDetailsState.Error -> ErrorView(s.exception)
    }
```

There are a bunch of options/parameters to do the same in 3.x but I don't have all the details right now. If you can't use 4.x let me know and I'll dig but if you can, it'll certainly be simpler.

**Comment by sonatard** [comment]
Thank you!

We're excited for version 4. We're thinking about using it, but it's in Alpha and that worries us. Is it too early to use it in our main product? We're okay with API changes, but we'd like to avoid using it if there are still unstable like crashes.

**Comment by martinbonnin** [comment]
> We're okay with API changes, but we'd like to avoid using it if there are still unstable like crashes.

My moto is "alpha is about API stability, not feature stability". If you're shipping a lib then do not use alphas because transitively upgrading apollo will break but in an app it should be fine.

Of course it's not as battle tested as 3.x but we do have more than 2k tests all passing and I'd love to get to a point where it's OK to use the alphas in production. 

In all cases, in 3.x, you should have `ApolloCall.emitCacheMisses(true)` to emulate the 4.x behaviour. KDoc is [there](https://www.apollographql.com/docs/kotlin/kdoc/apollo-normalized-cache/com.apollographql.apollo3.cache.normalized/emit-cache-misses.html?query=fun%20%3CT%3E%20MutableExecutionOptions%3CT%3E.emitCacheMisses(emitCacheMisses:%20Boolean):%20MutableExecutionOptions%3CT%3E) (it's the 4.x KDoc because we're only hosting one version of the KDoc but it's still the same signature)

**Comment by sonatard** [comment]
I am developing an app, so I am thinking of using Alpha version. Thanks!!

**Comment by sonatard** [comment]
I have achieved my goal by updating to Apollo v4! Thank you!
