### ISSUE TITLE
Is there way to run task that expands all fragments in query or mutation?

### ISSUE THREAD

**Issue by snijsure** [apollographql/apollo-kotlin#5111]
### Question

I have a query that looks like this:

```
query CurrentTopics() {
     ...BasicTopicInformation
}

```
And fragment looks like

```
fragment BasicTopicInformation on Topic {
    displayName
    viewCount
}
```

What I want is a graphQL file that expands the BasicTopicInformation inside the CurrentTopics query?

Probably GQL compiler does do this, because I see that expanded query in the kotlin file that gets generated, but couldn't locate that intermediate file. Is there way I can "capture" fully expanded query?

**Comment by martinbonnin** [comment]
You could use [Apollo AST](https://www.apollographql.com/docs/kotlin/advanced/apollo-ast/) to parse the GraphQL and substitute your fragments with their fields. In general though it's not an easy problem because fragments have type conditions that may or may not be fullfilled.

So for a given query, you might end up with several possible full expanded queries.

May I ask What's the use case for this? Maybe there's another solution that would accomplish the goal.

**Comment by snijsure** [comment]
What we really want to create a easy way to figure out what all fields in the schema does a specific query use. In the example above I can say  `CurrentTopics` uses fields `displayName` and `viewCount` from `Topic`

We have project with 100 queries and 62 fragments. 

When folks implementing backend service come and say tell us what all queries use field 'viewCount' on Topic it is hard to provide that answer! 

That is why I was looking for "flattened"  .graphql output for a query.

I guess I can just print `OPERATION_DOCUMENT`  for each query, that seems brute force if there is no other way, I can try that.

**Comment by snijsure** [comment]
That is amazing @martinbonnin  thank you for both those pointers. 🙇🏽‍♂️

Gives me something to try this weekend ;)

**Comment by martinbonnin** [comment]
Awesome 😃  . I'll close this issue for now. If you have questions over the week end, feel free to comment here and I'll reopen. Happy hacking!
