### ISSUE TITLE
Exist basic scalar type in downloaded schema and got Schema errors

### ISSUE THREAD

**Issue by sonatard** [apollographql/apollo-kotlin#5126]
### Question

<img width="781" alt="スクリーンショット 2023-07-26 13 11 38" src="https://github.com/apollographql/apollo-kotlin/assets/1586910/8a13fadc-376c-4059-8d06-c2a52bb2721d">

When I download the Schema with `gradlew :app:downloadApolloSchema` , the basic scalar type(ID, Int, Float...) exists in Schema file. Probably because of this, Android Studio is throwing an error, but how should I deal with this?

There is no problem with the operation such as building or sending requests.

Also, I sometimes write code to parse GraphQL schemas in Go, but I get the same error there and cannot parse it. Should the Go GraphQL parser be made not to throw an error, or should the schema not include a basic scalar type, which is correct?

**Comment by martinbonnin** [comment]
Hi 👋 . This is a known [issue in the GraphQL IntelliJ plugin](https://github.com/JetBrains/js-graphql-intellij-plugin/issues/665). These types needs to be in the schema because there exists several versions of them (deprecated input fields, repeated directives, etc... have been introduced more recently). And we need to know what version is used to do proper validation.

**Comment by martinbonnin** [comment]
It's affecting validation and/or introspection. Take the [latest builtin `__InputValue` type definition](https://spec.graphql.org/draft/#sel-GAJXNFAD0HAAC8IBmuX):

```graphql
type __InputValue {
  name: String!
  description: String
  type: __Type!
  defaultValue: String
  isDeprecated: Boolean!
  deprecationReason: String
}
```

And write this query:

```graphql
{
  __schema {
    types {
      inputFields {
        isDeprecated
      }
    }
  }
}
```

It will validate well for Apollo Kotlin because `isDeprecated` is in the schema. Now if you try to execute this against an [older version of the spec](https://spec.graphql.org/October2016/#sec-The-__InputValue-Type) that doesn't know about deprecated input fields, this query will error all the time. This is what we want to avoid by validating the queries client side.

**Comment by sonatard** [comment]
> When representing a GraphQL schema using the type system definition language, all built-in scalars must be omitted for brevity.
> https://spec.graphql.org/draft/#sec-Scalars.Built-in-Scalars

@martinbonnin Hi! I found this section in GraphQL Draft spec.
It seems to me that built-in scalars should not exist in the schema file. What do you think?

**Comment by martinbonnin** [comment]
Good catch, TIL! I'll remove them. It's only about builtin scalars though, not the introspection types or directives so there will be still some warnings for the time being but @BoD added a fix to the IntelliJ plugin [there](https://github.com/apollographql/apollo-kotlin/pull/5131)

**Comment by martinbonnin** [comment]
PR [here](https://github.com/apollographql/apollo-kotlin/pull/5132/files)

**Comment by sonatard** [comment]
Thanks 👍

**Comment by martinbonnin** [comment]
@sonatard: for the record, I opened [this PR](https://github.com/graphql/graphql-spec/pull/1036) in the GraphQL spec to explicit how introspection types should be handled in SDL. The tldr; is that it's not easy and will probably require to change to introspection and how servers declare their capabilities to other tools. You can read more in yesterday's [working group meeting notes](https://github.com/graphql/graphql-wg/blob/969c94f83fa1cdeeb9d015d368f2efec0c47aee7/notes/2023/2023-08.md)

**Comment by martinbonnin** [comment]
Thinking more about this, one actionable item for us is to add to the builtin types.

```graphql
# noinspection GraphQLTypeRedefinition
```

At least it'll remove the warning until the spec moves forward

**Comment by martinbonnin** [comment]
3 changes in `4.0.0-alpha.3`:

* scalars are not written by default in SDL
* other types have a `# noinspection GraphQLTypeRedefinition` comment to ignore the warning
* the Apollo IJ plugin itself is going to ignore the warning

I'll close this issue again as I believe there nothing more we can do in the current state of things. For discussions about how to handle full schemas in the GraphQL spec, see https://github.com/graphql/graphql-wg/issues/1367
