### ISSUE TITLE
How to run a query on mutation cache data

### ISSUE THREAD

**Issue by yuvaraj119** [apollographql/apollo-kotlin#5137]
### Question

First make a call mutation with input unique id and saving the response to cache(sqlite) 
Next do a query on cached data with its unique id 
Expected it should return the data referenced with id but it returns error with Object 'QUERY_ROOT' has no field named x

Also extended the mutation and query unique keyFields id in extra.graphql

Second scenario
When I run the same mutation with unique id with FetchCacheOnly, but it always makes a Network call and returns the result.

Either Query should be working or Mutation cache should be working neither is working here. 
Every time calling the api is not a good way.
Correct me if i'm doing any thing incorrect.

**Comment by BoD** [comment]
Hi! I believe it is probably expected that the first scenario doesn't work because the result of a query cannot be inferred if wasn't executed at least once - but it's hard to know for sure without seeing your code.

I recommend calling `println(NormalizedCache.prettifyDump(apolloClient.apolloStore.dump()))` to see the contents of your cache after the first mutation, this is often very useful to debug such issues.

For the second scenario: the network call is expected because a mutation with cache-only doesn't really make sense (you can't mutate if you don't reach the server) - so the fetch policy is essentially ignored for mutations. If your aim is to modify the cache locally, you could use the [ApolloStore APIs](https://www.apollographql.com/docs/kotlin/caching/store#writing-operation-data) instead.

**Comment by yuvaraj119** [comment]
@BoD  - You are right, I had a code to insert the mutation response writeToCacheAsynchronously(true) which caused the other query to run parllel'ly before insertion of response.
with `println` i'm able to figure out the issue.
Now I am able to query the mutation response data saved in cache.
@BoD Thanks!
