### ISSUE TITLE
What are the conditions for a Normalized Cache Hit?

### ISSUE THREAD

**Issue by sonatard** [apollographql/apollo-kotlin#5157]
### Question

I am using a query like the one below, and I expect that even when the languageCode or countryCode changes, it will not hit the cache and will send a request to the network. Is this correct?

```
query StorefrontProductPage($productID: ID!, $countryCode: CountryCode!, $languageCode: LanguageCode!) @inContext(country: $countryCode, language: $languageCode) {
    product(id: $productID) {
        id
        name
    }
}
```

**Comment by martinbonnin** [comment]
Yes, that's correct, arguments are used in cache keys so different argument values will store different data. And if no data is there for a given set of arguments, it'll emit a cache miss

**Comment by BoD** [comment]
Just to add to what @martinbonnin said, in your example, since only `productID` is used in the field, `countryCode` and `languageCode` won't be considered to check the cache. So even if they change, you could still get cache hits, as long as a value for `productID` is cached.

**Comment by martinbonnin** [comment]
100% what @BoD says, I completely missed that `languageCode` and `countryCode` were variables but only used in directives, not actual field arguments. `productID` is indeed the only one that's important for cache purposes.

**Comment by sonatard** [comment]
Thanks!
This is Shopify Storefront API, and since the response changes according to the languageCode and countryCode, I would like to expect that it will not hit the cache.

**Comment by martinbonnin** [comment]
Apollo Kotlin doesn't assume anything about custom directive so they are not taken into account for cache purposes.

Looking at the [@inContext](https://shopify.dev/docs/custom-storefronts/building-with-the-storefront-api/markets/international-pricing) documentation, looks like it's used for localization? Since this is something that is not changing very often, I would recommend you either clear the cache when the country or language change or create different `ApolloClient` using different caches when this happens.

For an example, we're doing something similar in Confetti when the conference [changes](https://github.com/joreilly/Confetti/blob/main/shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ApolloClientCache.kt#L106). It's a different use case but the underlying mechanism could be the same.

**Comment by sonatard** [comment]
OK. I think I clear the cache.
Thank you always for your quick response😄
