### ISSUE TITLE
Skip / Include optimization on Apollo Android Client 

### ISSUE THREAD

**Issue by snijsure** [apollographql/apollo-kotlin#5265]
### Question

We have lots of GraphQL queries in our product that use conditional include and skips.

From what I understand, even if your query contains skip and include the server still has to create a query plan, that includes elements that will be skipped based on parameters, which can be time consuming.

Is there a way to optimize the query that is being sent to the server, on the client side, that evaluates the skip/include, thus sending already optimized query to the server?

**Comment by martinbonnin** [comment]
Hi 👋 

> From what I understand, even if your query contains skip and include the server still has to create a query plan, that includes elements that will be skipped based on parameters, which can be time consuming.

It depends your server and I'm not the expert there but mostly yes. The server has to run validation and create som form of query plan. The query plan can be as simple as running the execution part of the spec where the central part is collecting all fields. In that case, the server would have to lookup the `@skip`/`@include` directive for each field which could take a bit of time but I would expect this to be negligeable in the grand scheme of things. 

> Is there a way to optimize the query that is being sent to the server, on the client side, that evaluates the skip/include, thus sending already optimized query to the server?

You could use [Apollo AST](https://www.apollographql.com/docs/kotlin/advanced/apollo-ast/) to modify your queries at runtime and prune the skipped parts of your query but that's some work to get right and it's taking the risk of a disconnect with the normalized cache because the normalized cache will not see your runtime modification (should work but it's fragile)

All it all, I'd recommend to:

1. Measure what's gained from removing the `@skip` parts by sending both versions to your server and see which one is faster. You might have to ask your backend team for insights about resource usage if the difference doesn't show in round trip times.
2. Investigate [persisted queries](https://www.apollographql.com/docs/kotlin/advanced/persisted-queries/). If your app is performance sensitive, persisted queries will bring you potentially a lot of improvement by reducing the network transfer size as well as allowing the server to skip validation completely.

**Comment by martinbonnin** [comment]
Anything else we can help with here?

**Comment by martinbonnin** [comment]
Closing for now, please leave a comment if you want us to reopen.
