### ISSUE TITLE
IntelliJ Plugin complains about `id` being unused, but afaiu I do want that to stay there as it's the cache ID I've set in extra.graphqls

### ISSUE THREAD

**Issue by StylianosGakis** [apollographql/apollo-kotlin#5386]
### Question

I got a query like this
```
query ChatMessages($until: Instant) {
  chat(until: $until) {
      id
    hasNext
    nextUntil
    messages {
      ...MessageFragment
    }
  }
}
```
Then in my extra.graphqls I got this
```
extend type Chat @typePolicy(keyFields: "id")
```
But in my code I do not really use `id` in some way.

The plugin suggests that I remove `id` from there, but I *think* that I want to keep that there for the key in the normalized cache to be generated correctly. Is that the case here, or can I just remove it?
If I should not remove it, is there something that I can do for the plugin to understand that this is sort of an exception to the rule of removing unused fields?

**Comment by BoD** [comment]
You can remove it from your query, as the codegen will automatically include it for you since it's part of the `keyFields`.

However, you could have other cases where you need to select fields even though they're not used in the Kotlin code, for the cache. In this case, the plugin will falsely warn that they are unused. To work around this, in the 'quick fix' dialog there should be an option "suppress for field" to suppress the warning with a comment in the query, and an option "Ignore field type.field" to add the field in the plugin's settings to globally never warn for this field (and then you can manage the list of ignored fields by going to "Edit inspection profile settings".)

<img width="519" alt="Screenshot 2023-11-21 at 11 57 56" src="https://github.com/apollographql/apollo-kotlin/assets/372852/e4cf566d-b195-4af1-aa92-adaa1fc7b2ca">

**Comment by StylianosGakis** [comment]
Oh wow that is definitely news to me, is that documented too? I didn't know specifying the keyfield in the extra.graphqls file also did that, that is super convenient, and totally makes sense in hindsight. I wonder, where does this happen exactly in the apollo-kotlin code? If I use the wrong string in the extra file (since it's untyped there, you just type strings) does it just fallback to not adding it at all?

And what a nice thing for the plugin to add a quick fix for this, and even a global storage for it. I guess it would make sense for cache reasons but when it's not the keyfield at the same time.

Thanks a lot for explaining this to me!

**Comment by StylianosGakis** [comment]
Perfect, thank you for explaining this to me!
