### ISSUE TITLE
Need no-op debug server

### ISSUE THREAD

**Issue by ber4444** [apollographql/apollo-kotlin#5643]
### Use case

`import com.apollographql.apollo3.debugserver.ApolloDebugServer` will break the release builds since your docs suggest to only include this dependency in the debug build type

### Describe the solution you'd like

  `releaseImplementation("com.apollographql.apollo3:apollo-debug-server-noop:4.0.0-beta.4")`

**Comment by BoD** [comment]
Hi!

You should be able to have the import only in your debug build, by doing something like this:

`app/src/debug/kotlin/yourpackage/ApolloDebugServer.kt`:

```kotlin
fun ApolloClient.registerApolloDebugServer() {
    ApolloDebugServer.registerApolloClient(this)
}
```

`app/src/main/kotlin/yourpackage/ApolloDebugServer.kt`:

```kotlin
fun ApolloClient.registerApolloDebugServer() {
    // no-op
}
```

and call it where you configure your client:

```kotlin
val apolloClient = ApolloClient.Builder() 
  // (...)
  .build()
  .registerApolloDebugServer()
```

[Here’s an example](https://github.com/joreilly/Confetti/pull/1042/files?w=1) of that, albeit a tad more complicated because it’s a KMP app.

Would that work for you?

**Comment by ber4444** [comment]
Excellent, thanks!
