### ISSUE TITLE
4.0.0 Pagination scenario: `CacheAndNetwork` emits the incoming data as-is, rather than the merged result from the cache

### ISSUE THREAD

**Issue by ChlorUpload** [apollographql/apollo-kotlin#5818]
### Question

When collecting the flow returned by `toFlow` constructed with the `CacheAndNetwork` fetch policy, the second emitted data consists of the incoming data as-is, rather than the merged result from the cache.

I'm currently in the process of implementing relay-style-pagination in version 4.0.0-beta.5, utilizing ConnectionRecordMerger. I've confirmed that the existing and incoming data merge correctly in the cache. However, `toFlow` emits the merged data from the cache, while the incoming data is emitted as-is. Consequently, the size of the array in the collected data appears as follows: 5, 10, 5, 15, 5, 20, 5, 25, 5, 30, 5, 35, ...

Is it intentional for `CacheAndNetwork` fetch policy to emit incoming data? This behavior appears to differ from that of `apollo-react`.

**Comment by BoD** [comment]
Hi! This is the expected behavior, while I can see that it is not very practical. 

When using the pagination support, it makes more sense to use
- [`watch`](https://www.apollographql.com/docs/kotlin/v4/caching/query-watchers) to observe the merged list 
- `NetworkOnly` to fetch new pages

You can see an example of doing this a sample app [here](https://github.com/BoD/ApolloKotlinPaginationSample/blob/incubating-pagination/app/src/main/java/com/example/apollokotlinpaginationsample/repository/Apollo.kt#L55).

Is there a case that I'm not seeing where `CacheAndNetwork` would be preferable?

**Comment by ChlorUpload** [comment]
I checked your sample app. Thank you!
I have a simple question. If I want to refresh the list and load the data from the beginning (such as `refetch` in `apollo-react`), should I clear the cache manually?

**Comment by BoD** [comment]
One simple way to do this is to fetch the 1st page again from the network (`FetchPolicy.NetworkOnly`), which will [interpreted](https://github.com/apollographql/apollo-kotlin/blob/01e6ca56143400196f2faf7482e475c45aa1abdb/libraries/apollo-normalized-cache-api-incubating/src/commonMain/kotlin/com/apollographql/apollo3/cache/normalized/api/RecordMerger.kt#L185) by the `ConnectionRecordMerger` as a reset signal.

You could also clear the cache manually via `ApolloStore` API, but the above is simpler.
