### ISSUE TITLE
Questions about new ApolloCompilerPlugin API

### ISSUE THREAD

**Issue by edenman** [apollographql/apollo-kotlin#5851]
### Question

Looking at the new `ApolloCompilerPlugin` stuff in 4.0 beta 6.  Coming from 4.0 beta 4 where we have an `operationIdGenerator` and we're also setting a `compilerKotlinHooks`.  I converted the compilerKotlinHooks to a `ApolloCompilerPlugin` but then I get this error `Apollo: using ApolloCompilerPlugin and operationOutputGenerator/operationIdGenerator/packageNameGenerator at the same time is not supported. See https://go.apollo.dev/ak-compiler-plugins for more details.`

Sounds like the new recommended approach is to have a single plugin that does all of this stuff?  If that's the case,

- Is `OperationDescriptor.source` the equivalent of `OperationIdGenerator.apply`'s `operationDocument` param?
- Is there any way to access the `org.gradle.api.logging.Logger` from the compiler plugin?  
- Is there any way to access gradle params like `gradle.startParameter.isOffline` from the plugin?

For context, this is our old `operationIdGenerator`:
```
        private val isRunningOnCi = System.getenv("CI") != null

        operationIdGenerator =
            if (gradle.startParameter.isOffline || isRunningOnCi) {
                OfflineIdOperationGenerator(logger)
            } else {
                serverOperationIdGenerator
            }
```

(Let me know if you'd prefer to discuss this on Slack, I just figured there's not much discussion on this stuff yet so it might be more helpful to be more publicly searchable)

**Comment by martinbonnin** [comment]
Hey! Thanks for posting this. GitHub definitely has better SEO so that's a good place 👍

> Sounds like the new recommended approach is to have a single plugin that does all of this stuff?

Yes, it'll ultimately allow us to isolate the compiler into its own classloader so we can remove the current relocation we're doing and more generally separate the concerns.

> Is OperationDescriptor.source the equivalent of OperationIdGenerator.apply's operationDocument param?

Yup, correct. I'll make a migration guide for this. 

> Is there any way to access the org.gradle.api.logging.Logger from the compiler plugin?

You might be able to add `gradleApi()` to your compiler plugin and call `Logging.getLogger()` but I wouldn't recommend it. We might want to isolate the plugin even more. I'll look at what KSP is doing. The setup is the similar, in the end I think it should match. 

> Is there any way to access gradle params like gradle.startParameter.isOffline from the plugin?

I think adding codegenerating them using something like `BuildConfigFields` would work ([this part of the doc](https://www.apollographql.com/docs/kotlin/v4/advanced/compiler-plugins/#passing-arguments-to-your-apollo-compiler-plugin))? It's not optimal because this value changing means you have to recompiler your plugin but in practice it shouldn't be too much of an issue.

KSP has [`args`](https://kotlinlang.org/docs/ksp-quickstart.html#pass-options-to-processors) for this but from a quick cursory look it doesn't provide type safety (it looks all string based). I'll dig more.

**Comment by martinbonnin** [comment]
Re: logging, looking at KSP [source code](https://github.com/google/ksp/blob/c3de1a589b71652e410a38a3a96320c7551bcd9d/common-deps/src/main/kotlin/com/google/devtools/ksp/KspGradleLogger.kt#L21), looks like it is all `System.out` based and they're passing the loglevel to the task. We could do the same so that at least `./gradlew -d`, `./gradlew -i`, etc... would be forwarded to the Apollo compiler plugin logs. Would that work?

**Comment by edenman** [comment]
> > Is there any way to access gradle params like gradle.startParameter.isOffline from the plugin?
> 
> I think codegenerating them using something like `BuildConfigFields` would work ([this part of the doc](https://www.apollographql.com/docs/kotlin/v4/advanced/compiler-plugins/#passing-arguments-to-your-apollo-compiler-plugin))? It's not optimal because this value changing means you have to recompile your plugin but in practice it shouldn't be too much of an issue.
> 
> KSP has [`args`](https://kotlinlang.org/docs/ksp-quickstart.html#pass-options-to-processors) for this but from a quick cursory look it doesn't provide type safety (it looks all string based). I'll dig more.

Yeah I'm wary of the `BuildConfigFields` approach triggering unnecessary module rebuilds but not sure if that's a real concern.  I'm a bit out of my depth here.  Maybe we could set it as a system env var?

**Comment by martinbonnin** [comment]
> set it as a system env var?

The issue is we need to make Gradle aware of any parameter for up-to-date checks, etc... If you have several parameters, it means either serializing them all to a single Gradle input (probably what KSP is doing) or something else (maybe pass a Map or so). This week is packed already but I'll look into it early next week.

**Comment by martinbonnin** [comment]
First drop for parameters and logger [here](https://github.com/apollographql/apollo-kotlin/pull/5865)

**Comment by edenman** [comment]
> > Is there any way to access gradle params like gradle.startParameter.isOffline from the plugin?
> 
> I think codegenerating them using something like `BuildConfigFields` would work ([this part of the doc](https://www.apollographql.com/docs/kotlin/v4/advanced/compiler-plugins/#passing-arguments-to-your-apollo-compiler-plugin))? It's not optimal because this value changing means you have to recompile your plugin but in practice it shouldn't be too much of an issue.
> 
> KSP has [`args`](https://kotlinlang.org/docs/ksp-quickstart.html#pass-options-to-processors) for this but from a quick cursory look it doesn't provide type safety (it looks all string based). I'll dig more.

Did you turn anything up on this one?

**Comment by martinbonnin** [comment]
There is `argument()` in latest SNAPSHOTs ([doc PR](https://github.com/apollographql/apollo-kotlin/pull/5866/files#diff-78cb5d4e5c03f2e7734ae3fe8d2923e012d0e6020bab1de8ee149c97227fe5e8R107)):

```kotlin
apollo {
  service("service") {
    packageName.set("com.example")

    // Add your plugin to the Apollo compiler classpath
    plugin(project(":apollo-compiler-plugin")) {
      argument("token", token) 
    }
  }
}
```

Let me know what you think. Note this also moves from `ApolloCompilerPlugin` to `ApolloCompilerPluginProvider`

**Comment by edenman** [comment]
Woof I am bad at reading, totally mis-parsed `First drop for parameters and logger` to only be about the logger stuff.

The beta7 snapshot is great, looking forward to release!  Thanks again :)

**Comment by martinbonnin** [comment]
beta.7 is available now

**Comment by kenyee** [comment]
Noticed this in the latest apollo graphql output:
13:39:21 Apollo: using ApolloCompilerPluginProvider is deprecated. Please use ApolloCompilerPlugin directly.

Is there a migration guide?
How do you tell apollo to use our subclass of ApolloCompilerPlugin w/o using ApolloCompilerPluginProvider? 🤔

**Comment by martinbonnin** [comment]
No migration guide planned here but you can take a look at the [v5 documentation](https://www.apollographql.com/docs/kotlin/advanced/compiler-plugins).

It's basically a ServiceLoader API so you can do just like your provider but with the plugin directly. I'll tweak the message a bit to make this more explicit.

**Comment by martinbonnin** [comment]
I don't think there's a DSL for it. It has to be done using the resource thing. 

Will add a link to the warning 👍
