### ISSUE TITLE
Why is latest beta-6 using Kotlin 2.0.0-RC1?

### ISSUE THREAD

**Issue by damianpetla** [apollographql/apollo-kotlin#5856]
### Question

Hey! I will be honest and I admin that I haven't tried new beta-6 yet but the main reason was seeing Kotlin 2.0.0-RC1. We are using KMP with Apollo and every time there is Kotlin upgrade things break all over the place and we have to update different libs etc.
So my question is: was it really necessary to upgrade it to Kotlin 2.0.0? If so I am curious why, if not, would it be possible for the future to stay on the latest stable Kotlin version please?

**Comment by martinbonnin** [comment]
Hi 👋 The general idea is:

* stable Apollo versions (3.8 right now) are conservative when it comes to Kotlin versions and will always use latest stable (or even older one if there's no reason to upgrade)
* alphas/beta use latest KGP but target stable `apiVersion`/`languageVersion`. 
  * On JVM projects, there should be no issue using `apollo:4.0.0-beta.6` with Kotlin `1.9.x`. 
  * It's a bit less clear on Native/JS because there's no `languageVersion` support for native ([related Youtrack](https://youtrack.jetbrains.com/issue/KT-66755/Native-add-support-for-languageVersion))

What we've seen so far is that KMP projects usually need to track the Kotlin version pretty closely because that part of the ecosystem is moving quite fast. If it's slowing down we'll consider being more conservative for alphas/betas as well but being able to use latest build tools while targetting older binaries seems pretty important for the ecosystem overall. I wouldn't give up on this without trying it a bit more. If you have specific issues, please share them so we can make sure the ecosystem evolves smoothly.

**Comment by martinbonnin** [comment]
@damianpetla for the record, I asked the question of `languageVersion` support for non-JVM at KotlinConf and looks like it's not coming any time soon. 

One argument is that K/N users need to update their KGP version frequently to track Xcode releases so supporting older versions is not very high on the todo list. 

As for us, I think we'll continue doing the following:

* update KGP as soon as possible and set languageVersion = n - 1 
* gives ~1 year of upgrade time for JVM
* non-JVM users will have to update KGP in their build before they can update to the latest Apollo version. They can obviously keep using the older versions of Apollo.
