### ISSUE TITLE
RetryOnNetworkErrorInterceptor should be configurable

### ISSUE THREAD

**Issue by edenman** [apollographql/apollo-kotlin#5982]
### Use case

We currently have our own interceptor to handle retries on network errors, but 
1) it also retries if the http status code is 5xx
2) we'd like the ability to configure the backoff duration

Not a huge deal (we can obviously keep using our own) but I'd like to switch to using NetworkMonitor+failFastIfOffline+retryOnError if possible

**Comment by martinbonnin** [comment]
Agreed something needs to be done there. I've always tried to avoid giving "privileged" roles to interceptors so that they remain a generic list but the order matters (+ knowing whether a specific kind interceptor was set is also interesting information if we want a default behaviour). I'll look into this.
