### ISSUE TITLE
Failed HTTP response does not contain exception

### ISSUE THREAD

**Issue by jiri-muller** [apollographql/apollo-kotlin#6271]
### Version

4.1.0

### Summary

There is no exception in response when HTTP request fails (i.e 401). 

Response in 4.1.0
![image](https://github.com/user-attachments/assets/b70da80e-eb6f-462c-8538-04a274bbb850)

Response in 4.0.1 
![image](https://github.com/user-attachments/assets/b56fd0cb-51db-40a7-984b-22c6f0bbb957)

### Steps to reproduce the behavior

1) Execute query to endpoint that returns HTTP 401
2) Check ApolloResponse content - There is no exception, data or error

### Logs

```
(Your logs here)
```

**Comment by martinbonnin** [comment]
Thanks for sending this. This is due to the support for `application/graphql-response+json` (see https://github.com/apollographql/apollo-kotlin/blob/main/CHANGELOG.md#new-media-type-applicationgraphql-responsejson). 

This is an unfortunate behaviour change, alas I haven't found a way to provide a better update path and could probably be considered a bugfix.

If you want to restore the throwing behaviour, you can use an `ApolloInterceptor` for that (I'll send some code in a bit) but in general, I would recommend parsing the `errors` to get the information you are looking for. It usually contains more information than the `ApolloHttpException`.

PS: you can read more details about the new content-type in the [GraphQL over HTTP spec](https://graphql.github.io/graphql-over-http/)

**Comment by jiri-muller** [comment]
@martinbonnin Thank you Martin! I was checking release notes but I totally missed this part. I will try to implement the interceptor.

**Comment by jiri-muller** [comment]
Hmm looking at the it again I don't think `ApolloInterceptor` will help me. AFAIK it has access only to the same `ApolloResponse` that is missing the exception. Also I don't care about throwing behavior much I just need to identify failed requests and I don't think that checking that (data == null) will be enough. 

I implemented `okhttp3.Interceptor` for underlying okHttp client and I can check the HTTP status there and if it's not 2xx I can throw exception that can caught in method calling `execute()`.

I did not read whole [GraphQL over HTTP spec](https://graphql.github.io/graphql-over-http/) specification but I would expect that if server is not returning `application/graphql-response+json` client should be able to handle potential error directly without interceptor in HTTP client...

**Comment by martinbonnin** [comment]
I'd say the key is using `executionContext[HttpInfo]` to retrieve the status code:

```kotlin
          .addInterceptor(object : ApolloInterceptor {
            override fun <D : Operation.Data> intercept(
                request: ApolloRequest<D>,
                chain: ApolloInterceptorChain,
            ): Flow<ApolloResponse<D>> {
              return chain.proceed(request).onEach {
                val httpInfo = it.executionContext[HttpInfo]
                if (httpInfo != null && httpInfo.statusCode !in 200..299) {
                  throw ApolloHttpException(httpInfo.statusCode, httpInfo.headers, null, "HTTP request failed")
                }
              }
            }
          })
```

> I just need to identify failed requests and I don't think that checking that (data == null) will be enough.

I'd recommend your server folks to include something in the GraphQL errors:

```json5
{
  "errors": [
    {
      "message": "AuthorizationFailed",
      "extensions": {
        "code": 401 // or something else, doesn't have to match HTTP codes.
      }
    }
  ]
}
```

Hope this helps!

**Comment by martinbonnin** [comment]
Closing for now, please leave a message if you want us to revisit
