### ISSUE TITLE
Expose the internal ApolloRequest<D>.fetchFromCache extension property

### ISSUE THREAD

**Issue by Emplexx** [apollographql/apollo-kotlin#6307]
### Use case

I am trying to implement a client-side rate limit in my application using an `ApolloInterceptor`, and since my client is configured with a normalized cache, the issue I'm running into is that I have no way of telling whether I should limit the request or not, since I don't know if it's going to the network (what I'm trying to limit, to spare the API I'm using), or to the cache. I tried to look through how normalized caching is implemented and found the `fetchFromCache` extension property. 

### Describe the solution you'd like

I would like that property to be public (potentially marked with `@ApolloInternal`?), or another way to tell if the `ApolloRequest` inside of an interceptor is going to the cache or not. Sorry if I got anything wrong

**Comment by martinbonnin** [comment]
Hi 👋 

In order to do that, I'd recommend registering your `ApolloInterceptor` **after** setting up the cache:

```kotlin
ApolloClient.Builder()
  .serverUrl("https://...")
  .normalizedCache(normalizedCacheFactory)
  .addInterceptor(myRateLimitingInterceptor)
```

This way, your interceptor will only be called if no request was found in the cache.

Alternatively, you could also use an [HttpInterceptor](https://www.apollographql.com/docs/kotlin/advanced/interceptors-http#apollo-http-interceptors).

**Comment by Emplexx** [comment]
Ah, I was under the impression that an interceptor would still be called in this scenario. This works for my use-case so I will close this issue. Thank you!
